In [1]:
import json
from pathlib import Path

notebook_path = Path(
    r"C:\Users\Hp\Documents\pulseiq\PQ-02_Star_Schema_Warehouse.ipynb"
)

with open(notebook_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

print("Saved PQ-02 cells:", len(nb["cells"]))
print("Saved outputs:", sum(
    len(c.get("outputs", []))
    for c in nb["cells"] if c["cell_type"] == "code"
))

Saved PQ-02 cells: 45
Saved outputs: 0

In [2]:
from pathlib import Path
import duckdb
import pandas as pd

# Project paths
PROJECT_ROOT = Path(r"C:\Users\Hp\Documents\pulseiq")
SOURCE_DB = PROJECT_ROOT / "05_Starter" / "pulseiq.duckdb"
WAREHOUSE_DB = PROJECT_ROOT / "05_Starter" / "pulseiq_warehouse.duckdb"

# Check that both databases exist
print("Project folder exists:", PROJECT_ROOT.exists())
print("Source database exists:", SOURCE_DB.exists())
print("Warehouse database exists:", WAREHOUSE_DB.exists())

assert SOURCE_DB.exists(), "Source database not found."
assert WAREHOUSE_DB.exists(), "Warehouse database not found."

# Connect to the separate warehouse database
con_dq = duckdb.connect(str(WAREHOUSE_DB))

# Attach the source database as read-only
attached_dbs = con_dq.execute("PRAGMA database_list").fetchdf()

if "source_db" not in attached_dbs["name"].astype(str).tolist():
    con_dq.execute(
        f"ATTACH '{SOURCE_DB.as_posix()}' AS source_db (READ_ONLY)"
    )

print("\nDatabase connections ready.")
display(con_dq.execute("PRAGMA database_list").fetchdf())

Project folder exists: True
Source database exists: True
Warehouse database exists: True

Database connections ready.

     seq               name                                               file
0  20777  pulseiq_warehouse  C:\Users\Hp\Documents\pulseiq\05_Starter\pulse...
1  22382          source_db  C:\Users\Hp\Documents\pulseiq\05_Starter\pulse...

In [3]:
for table_name in ["dq_checks_catalog", "dq_known_issues"]:
    print(f"\n{'=' * 60}")
    print(f"TABLE: {table_name}")
    print("=" * 60)

    df = con_dq.execute(
        f"SELECT * FROM source_db.raw.{table_name}"
    ).fetchdf()

    print("Rows:", len(df))
    print("Columns:", df.columns.tolist())
    display(df)

============================================================
TABLE: dq_checks_catalog
============================================================
Rows: 14
Columns: ['check_id', 'check_name', 'description', 'logic_sql_or_rule', 'severity', 'tolerance', 'frequency', 'owner', 'fix_guidance']

,check_id,check_name,description,logic_sql_or_rule,severity,tolerance,frequency,owner,fix_guidance
0,DQ-C01,Payroll equals ledger,Monthly payroll employer cost must equal ledge...,"SELECT month, p.cost - l.exp AS diff FROM payr...",Critical,0.01 INR,Every load,Finance Analytics,Check the payroll posting entry for that run
1,DQ-C02,Ledger balanced,Total debits equal total credits per journal e...,SELECT entry_id FROM fact_ledger GROUP BY entr...,Critical,0.005,Every load,Finance Analytics,Reject the entry and alert the ledger owner
2,DQ-C03,Unique payroll rows,One payroll row per employee per run.,"SELECT employee_id, run_id FROM fact_payroll G...",Critical,0,Every load,Payroll Analytics,Remove duplicate and trace its source
3,DQ-C04,No orphan employees,Every fact employee_id exists in dim_employee.,SELECT f.employee_id FROM fact_payroll f LEFT ...,Critical,0,Every load,Data Engineering,Fix the key or load the missing employee
4,DQ-C05,No attendance after exit,Attendance month must not be after the employe...,SELECT a.* FROM fact_attendance a JOIN dim_emp...,Warning,0,Every load,HR Analytics,Ask HR to confirm exit date or remove the row
5,DQ-C06,Unpaid leave deducted,Employees with unpaid absence days in attendan...,Compare fact_attendance.unpaid_absence_days wi...,Warning,0.5 days,Every load,Payroll Analytics,Review unpaid-leave mapping
6,DQ-C07,Invoice arithmetic,Invoice paid must not exceed total; balance mu...,SELECT invoice_id FROM fact_invoice WHERE amou...,Warning,0.01,Daily,Finance Analytics,Correct the payment record
7,DQ-C08,Expense arithmetic,Total must equal amount plus GST.,SELECT expense_id FROM fact_expense WHERE ABS(...,Warning,0.01,Daily,Finance Analytics,Correct the bill entry
8,DQ-C09,Task dates sensible,Completed date not before started date; Done t...,SELECT task_id FROM fact_task WHERE completed_...,Warning,0,Daily,Engineering Ops,Ask the team to fix the board data
9,DQ-C10,Leave dates sensible,Leave end date not before start date.,SELECT leave_request_id FROM fact_leave WHERE ...,Warning,0,Daily,HR Analytics,Fix swapped dates
10,DQ-C11,AI feeds are fresh,Prediction as-of dates within 7 days of the ba...,SELECT prediction_id FROM fact_attrition_risk ...,Warning,7 days,Every load,AI/ML,Ask the AI team to rerun scoring
11,DQ-C12,Dimension history does not overlap,Employee versions must not overlap in time.,SELECT a.employee_key FROM dim_employee a JOIN...,Critical,0,Every load,Data Engineering,Close the earlier version the day before the n...
12,DQ-C13,Pipeline freshness,Latest successful load within 24 hours.,SELECT MAX(finished_at) FROM etl_run_log,Critical,24 hours,Hourly,Data Engineering,Check scheduler and source availability
13,DQ-C14,Minimum group size,Aggregates shown to managers must cover at lea...,HAVING COUNT(DISTINCT employee_id) >= min_grou...,Critical,NaN,On every query,Security / Analytics,Suppress the cell or combine groups

============================================================
TABLE: dq_known_issues
============================================================

CatalogException: Catalog Error: Table with name dq_known_issues does not exist!
Did you mean "dim_role"?

LINE 1: SELECT * FROM source_db.raw.dq_known_issues
                      ^

In [4]:

# List all tables visible in the connected DuckDB databases
source_tables = con_dq.execute("SHOW ALL TABLES").fetchdf()

print("Total tables found:", len(source_tables))
display(source_tables)

# Filter for data-quality and unlock-related tables
table_name_col = next(
    (col for col in source_tables.columns if col.lower() == "table_name"),
    None
)

if table_name_col:
    possible_tables = source_tables[
        source_tables[table_name_col].astype(str).str.contains(
            "dq|quality|issue|unlock|check",
            case=False,
            na=False
        )
    ]
    print("\nPossible data-quality and unlock tables:")
    display(possible_tables)

Total tables found: 54

,database,schema,name,column_names,column_types,temporary
0,pulseiq_warehouse,warehouse,dim_account,"[account_code, account_name, account_type, nor...","[BIGINT, VARCHAR, VARCHAR, VARCHAR, DOUBLE, VA...",False
1,pulseiq_warehouse,warehouse,dim_client,"[client_id, client_name, industry, city, state...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, ...",False
2,pulseiq_warehouse,warehouse,dim_date,"[date, date_key, year, quarter, month_number, ...","[DATE, BIGINT, BIGINT, BIGINT, BIGINT, VARCHAR...",False
3,pulseiq_warehouse,warehouse,dim_department,"[department_id, department_name, cost_center, ...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR]",False
4,pulseiq_warehouse,warehouse,dim_employee,"[employee_key, employee_id, full_name, gender,...","[BIGINT, VARCHAR, VARCHAR, VARCHAR, DATE, DATE...",False
5,pulseiq_warehouse,warehouse,dim_leave_type,"[leave_type_code, leave_type_name, pay_type, a...","[VARCHAR, VARCHAR, VARCHAR, BIGINT, VARCHAR, V...",False
6,pulseiq_warehouse,warehouse,dim_location,"[work_location, state, city_tier, tier_number]","[VARCHAR, VARCHAR, VARCHAR, BIGINT]",False
7,pulseiq_warehouse,warehouse,dim_role,"[role_id, department_id, role_title, level, gr...","[VARCHAR, VARCHAR, VARCHAR, BIGINT, VARCHAR, B...",False
8,pulseiq_warehouse,warehouse,dim_sprint,"[sprint_id, sprint_name, start_date, end_date,...","[VARCHAR, VARCHAR, DATE, DATE, BIGINT, VARCHAR]",False
9,pulseiq_warehouse,warehouse,dim_team,"[team_id, team_name, department_id, team_lead_...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, BIGINT, V...",False
10,pulseiq_warehouse,warehouse,dim_vendor,"[vendor_id, vendor_name, primary_expense_accou...","[VARCHAR, VARCHAR, BIGINT, BIGINT, VARCHAR, VA...",False
11,pulseiq_warehouse,warehouse,dq_results,"[check_id, check_name, severity, status, faili...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, INTEGER, ...",False
12,pulseiq_warehouse,warehouse,etl_run_log,"[run_id, pipeline_name, started_at, completed_...","[VARCHAR, VARCHAR, TIMESTAMP, TIMESTAMP, VARCH...",False
13,pulseiq_warehouse,warehouse,fact_anomaly,"[result_id, source_dataset, record_id, employe...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, DATE, DOU...",False
14,pulseiq_warehouse,warehouse,fact_attendance_monthly,"[attendance_fact_id, employee_id, date_key, em...","[VARCHAR, VARCHAR, BIGINT, BIGINT, VARCHAR, BI...",False
15,pulseiq_warehouse,warehouse,fact_attrition_risk,"[prediction_id, employee_id, as_of_date_key, d...","[VARCHAR, VARCHAR, BIGINT, VARCHAR, DATE, DOUB...",False
16,pulseiq_warehouse,warehouse,fact_expense,"[expense_id, expense_date, expense_date_key, c...","[VARCHAR, DATE, BIGINT, BIGINT, VARCHAR, VARCH...",False
17,pulseiq_warehouse,warehouse,fact_forecast,"[forecast_id, metric, department_id, forecast_...","[VARCHAR, VARCHAR, VARCHAR, DATE, DOUBLE, DOUB...",False
18,pulseiq_warehouse,warehouse,fact_headcount_monthly,"[date_key, month_start_date, department_id, he...","[BIGINT, DATE, VARCHAR, BIGINT, BIGINT, BIGINT...",False
19,pulseiq_warehouse,warehouse,fact_invoice,"[invoice_id, invoice_number, client_id, invoic...","[VARCHAR, VARCHAR, VARCHAR, BIGINT, DATE, DATE...",False
20,pulseiq_warehouse,warehouse,fact_invoice_payment,"[payment_id, invoice_id, payment_date_key, pay...","[VARCHAR, VARCHAR, BIGINT, DATE, DOUBLE, VARCH...",False
21,pulseiq_warehouse,warehouse,fact_leave,"[leave_request_id, employee_id, employee_key, ...","[VARCHAR, VARCHAR, BIGINT, VARCHAR, BIGINT, BI...",False
22,pulseiq_warehouse,warehouse,fact_ledger,"[line_id, entry_id, date_key, entry_date, post...","[VARCHAR, VARCHAR, BIGINT, DATE, VARCHAR, VARC...",False
23,pulseiq_warehouse,warehouse,fact_payroll,"[payroll_item_id, run_id, employee_id, date_ke...","[VARCHAR, VARCHAR, VARCHAR, BIGINT, BIGINT, DA...",False
24,pulseiq_warehouse,warehouse,fact_task,"[task_id, team_id, sprint_id, assignee_employe...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, ...",False
25,source_db,raw,budget_payroll_dept_month,"[department_id, month, budget_payroll_cost]","[VARCHAR, DATE, BIGINT]",False
26,source_db,raw,data_contracts,"[feed, column_name, data_type, nullable, rule_...","[VARCHAR, VARCHAR, VARCHAR, BOOLEAN, VARCHAR, ...",False
27,source_db,raw,data_dictionary,"[sheet, column, data_type, description, null_c...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, BIGINT, D...",False
28,source_db,raw,dim_account,"[account_code, account_name, account_type, nor...","[BIGINT, VARCHAR, VARCHAR, VARCHAR, DOUBLE, VA...",False
29,source_db,raw,dim_client,"[client_id, client_name, industry, city, state...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, ...",False
30,source_db,raw,dim_date,"[date, date_key, year, quarter, month_number, ...","[DATE, BIGINT, BIGINT, BIGINT, BIGINT, VARCHAR...",False
31,source_db,raw,dim_department,"[department_id, department_name, cost_center, ...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR]",False
32,source_db,raw,dim_employee,"[employee_key, employee_id, full_name, gender,...","[BIGINT, VARCHAR, VARCHAR, VARCHAR, DATE, DATE...",False
33,source_db,raw,dim_leave_type,"[leave_type_code, leave_type_name, pay_type, a...","[VARCHAR, VARCHAR, VARCHAR, BIGINT, VARCHAR, V...",False
34,source_db,raw,dim_location,"[work_location, state, city_tier, tier_number]","[VARCHAR, VARCHAR, VARCHAR, BIGINT]",False
35,source_db,raw,dim_role,"[role_id, department_id, role_title, level, gr...","[VARCHAR, VARCHAR, VARCHAR, BIGINT, VARCHAR, B...",False
36,source_db,raw,dim_sprint,"[sprint_id, sprint_name, start_date, end_date,...","[VARCHAR, VARCHAR, DATE, DATE, BIGINT, VARCHAR]",False
37,source_db,raw,dim_team,"[team_id, team_name, department_id, team_lead_...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, BIGINT, V...",False
38,source_db,raw,dim_vendor,"[vendor_id, vendor_name, primary_expense_accou...","[VARCHAR, VARCHAR, BIGINT, BIGINT, VARCHAR, VA...",False
39,source_db,raw,dq_checks_catalog,"[check_id, check_name, description, logic_sql_...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, ...",False
40,source_db,raw,fact_anomaly,"[result_id, source_dataset, record_id, employe...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, DATE, DOU...",False
41,source_db,raw,fact_attendance_monthly,"[attendance_fact_id, employee_id, date_key, em...","[VARCHAR, VARCHAR, BIGINT, BIGINT, VARCHAR, BI...",False
42,source_db,raw,fact_attrition_risk,"[prediction_id, employee_id, as_of_date_key, d...","[VARCHAR, VARCHAR, BIGINT, VARCHAR, DATE, DOUB...",False
43,source_db,raw,fact_expense,"[expense_id, expense_date, expense_date_key, c...","[VARCHAR, DATE, BIGINT, BIGINT, VARCHAR, VARCH...",False
44,source_db,raw,fact_forecast,"[forecast_id, metric, department_id, forecast_...","[VARCHAR, VARCHAR, VARCHAR, DATE, DOUBLE, DOUB...",False
45,source_db,raw,fact_headcount_monthly,"[date_key, month_start_date, department_id, he...","[BIGINT, DATE, VARCHAR, BIGINT, BIGINT, BIGINT...",False
46,source_db,raw,fact_invoice,"[invoice_id, invoice_number, client_id, invoic...","[VARCHAR, VARCHAR, VARCHAR, BIGINT, DATE, DATE...",False
47,source_db,raw,fact_invoice_payment,"[payment_id, invoice_id, payment_date_key, pay...","[VARCHAR, VARCHAR, BIGINT, DATE, DOUBLE, VARCH...",False
48,source_db,raw,fact_leave,"[leave_request_id, employee_id, employee_key, ...","[VARCHAR, VARCHAR, BIGINT, VARCHAR, BIGINT, BI...",False
49,source_db,raw,fact_ledger,"[line_id, entry_id, date_key, entry_date, post...","[VARCHAR, VARCHAR, BIGINT, DATE, VARCHAR, VARC...",False
50,source_db,raw,fact_payroll,"[payroll_item_id, run_id, employee_id, date_ke...","[VARCHAR, VARCHAR, VARCHAR, BIGINT, BIGINT, DA...",False
51,source_db,raw,fact_task,"[task_id, team_id, sprint_id, assignee_employe...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, ...",False
52,source_db,raw,kpi_targets,"[month, department_id, attendance_rate_target,...","[DATE, VARCHAR, DOUBLE, DOUBLE, BIGINT, DOUBLE]",False
53,source_db,raw,metric_dictionary,"[metric_id, metric_name, business_definition, ...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, ...",False

In [5]:

# Find PQ-03 unlock files and known-issues files
search_terms = ("unlock", "pq-03", "known_issues", "known issues")

matches = [
    path for path in PROJECT_ROOT.rglob("*")
    if path.is_file()
    and any(term in path.name.lower() for term in search_terms)
]

print("Matching files found:", len(matches))

for path in matches:
    print(path)

Matching files found: 8
C:\Users\Hp\Documents\pulseiq\PQ-03_Data_Quality_Gatekeeper.ipynb
C:\Users\Hp\Documents\pulseiq\.ipynb_checkpoints\PQ-03_Data_Quality_Gatekeeper-checkpoint.ipynb
C:\Users\Hp\Documents\pulseiq\04_Validation_Vault\PQ-03_planted_issue_coverage.csv
C:\Users\Hp\Documents\pulseiq\04_Validation_Vault\unlock_PQ-03_dq_known_issues.csv
C:\Users\Hp\Documents\pulseiq\04_Validation_Vault\unlock_PQ-09_reconciliation_answer_key.csv
C:\Users\Hp\Documents\pulseiq\04_Validation_Vault\unlock_PQ-13_reference_summary_dept_month.csv
C:\Users\Hp\Documents\pulseiq\docs\PQ-03_data_quality_gatekeeper_report.md
C:\Users\Hp\Documents\pulseiq\.venv\Lib\site-packages\jedi\third_party\typeshed\stubs\ldap3\ldap3\extend\microsoft\unlockAccount.pyi

In [6]:

# Read the complete data-quality check catalog
dq_catalog = con_dq.execute("""
    SELECT *
    FROM source_db.raw.dq_checks_catalog
    ORDER BY check_id
""").fetchdf()

pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_rows", 50)

print("Total checks:", len(dq_catalog))
display(dq_catalog)

# Confirm the planted-issues file exists without opening its contents
issues_path = (
    PROJECT_ROOT
    / "04_Validation_Vault"
    / "unlock_PQ-03_dq_known_issues.csv"
)

print("\nPlanted-issues file exists:", issues_path.exists())

Total checks: 14

,check_id,check_name,description,logic_sql_or_rule,severity,tolerance,frequency,owner,fix_guidance
0,DQ-C01,Payroll equals ledger,Monthly payroll employer cost must equal ledger salary-related expense (5001-5005).,"SELECT month, p.cost - l.exp AS diff FROM payroll p JOIN ledger l USING(month) WHERE ABS(diff) > 0.01",Critical,0.01 INR,Every load,Finance Analytics,Check the payroll posting entry for that run
1,DQ-C02,Ledger balanced,Total debits equal total credits per journal entry.,SELECT entry_id FROM fact_ledger GROUP BY entry_id HAVING ABS(SUM(debit) - SUM(credit)) > 0.005,Critical,0.005,Every load,Finance Analytics,Reject the entry and alert the ledger owner
2,DQ-C03,Unique payroll rows,One payroll row per employee per run.,"SELECT employee_id, run_id FROM fact_payroll GROUP BY 1,2 HAVING COUNT(*) > 1",Critical,0,Every load,Payroll Analytics,Remove duplicate and trace its source
3,DQ-C04,No orphan employees,Every fact employee_id exists in dim_employee.,SELECT f.employee_id FROM fact_payroll f LEFT JOIN dim_employee d USING(employee_id) WHERE d.employee_id IS NULL,Critical,0,Every load,Data Engineering,Fix the key or load the missing employee
4,DQ-C05,No attendance after exit,Attendance month must not be after the employee exit month.,SELECT a.* FROM fact_attendance a JOIN dim_employee d ON a.employee_id = d.employee_id AND d.is_current = 'Y' WHERE d.exit_date IS NOT NULL AND a.period_end_date > LAST_DAY(d.exit_date),Warning,0,Every load,HR Analytics,Ask HR to confirm exit date or remove the row
5,DQ-C06,Unpaid leave deducted,Employees with unpaid absence days in attendance must show lop_days in payroll for the month.,Compare fact_attendance.unpaid_absence_days with fact_payroll.lop_days per employee-month,Warning,0.5 days,Every load,Payroll Analytics,Review unpaid-leave mapping
6,DQ-C07,Invoice arithmetic,Invoice paid must not exceed total; balance must not be negative.,SELECT invoice_id FROM fact_invoice WHERE amount_paid > total_amount OR balance_due < 0,Warning,0.01,Daily,Finance Analytics,Correct the payment record
7,DQ-C08,Expense arithmetic,Total must equal amount plus GST.,SELECT expense_id FROM fact_expense WHERE ABS(total_amount - (amount_excl_gst + gst_amount)) > 0.01,Warning,0.01,Daily,Finance Analytics,Correct the bill entry
8,DQ-C09,Task dates sensible,Completed date not before started date; Done tasks have a completed date.,SELECT task_id FROM fact_task WHERE completed_date < started_date OR (status = 'Done' AND completed_date IS NULL),Warning,0,Daily,Engineering Ops,Ask the team to fix the board data
9,DQ-C10,Leave dates sensible,Leave end date not before start date.,SELECT leave_request_id FROM fact_leave WHERE end_date < start_date,Warning,0,Daily,HR Analytics,Fix swapped dates
10,DQ-C11,AI feeds are fresh,Prediction as-of dates within 7 days of the batch date; scored_at within 24 hours of load.,SELECT prediction_id FROM fact_attrition_risk WHERE as_of_date < (SELECT MAX(as_of_date) FROM fact_attrition_risk) - 7,Warning,7 days,Every load,AI/ML,Ask the AI team to rerun scoring
11,DQ-C12,Dimension history does not overlap,Employee versions must not overlap in time.,SELECT a.employee_key FROM dim_employee a JOIN dim_employee b ON a.employee_id = b.employee_id AND a.employee_key < b.employee_key AND a.valid_to >= b.valid_from,Critical,0,Every load,Data Engineering,Close the earlier version the day before the next one starts
12,DQ-C13,Pipeline freshness,Latest successful load within 24 hours.,SELECT MAX(finished_at) FROM etl_run_log,Critical,24 hours,Hourly,Data Engineering,Check scheduler and source availability
13,DQ-C14,Minimum group size,Aggregates shown to managers must cover at least the minimum group size in the metric dictionary.,HAVING COUNT(DISTINCT employee_id) >= min_group_size,Critical,NaN,On every query,Security / Analytics,Suppress the cell or combine groups

Planted-issues file exists: True

In [7]:

# Inspect the warehouse tables used by the 14 checks
tables_to_inspect = [
    "fact_payroll",
    "fact_ledger",
    "dim_employee",
    "fact_attendance_monthly",
    "fact_leave",
    "fact_invoice",
    "fact_expense",
    "fact_task",
    "fact_attrition_risk",
]

for table_name in tables_to_inspect:
    print(f"\n{'=' * 55}")
    print(f"TABLE: warehouse.{table_name}")
    print("=" * 55)

    columns = con_dq.execute(
        f"DESCRIBE warehouse.{table_name}"
    ).fetchdf()

    display(columns[["column_name", "column_type"]])

# Check whether supporting tables exist in either database
all_tables = con_dq.execute("SHOW ALL TABLES").fetchdf()

for name in ["etl_run_log", "metric_dictionary", "dq_results"]:
    found = all_tables[all_tables["name"].str.lower() == name.lower()]
    print(f"\n{name}:")
    display(found[["database", "schema", "name"]] if not found.empty else found)

=======================================================
TABLE: warehouse.fact_payroll
=======================================================

            column_name column_type
0       payroll_item_id     VARCHAR
1                run_id     VARCHAR
2           employee_id     VARCHAR
3              date_key      BIGINT
4          employee_key      BIGINT
5       period_end_date        DATE
6         department_id     VARCHAR
7               role_id     VARCHAR
8          payable_days      DOUBLE
9              lop_days      DOUBLE
10  overtime_hours_paid      DOUBLE
11    variable_pay_type     VARCHAR
12  monthly_fixed_gross      BIGINT
13                basic      DOUBLE
14                  hra      DOUBLE
15           conveyance      DOUBLE
16              medical      DOUBLE
17    special_allowance      DOUBLE
18     earned_fixed_pay      DOUBLE
19         overtime_pay      DOUBLE
20         variable_pay      DOUBLE
21            gross_pay      DOUBLE
22          pf_employee      DOUBLE
23         esi_employee      DOUBLE
24     professional_tax      BIGINT
25                  tds      DOUBLE
26     other_deductions      BIGINT
27     total_deductions      DOUBLE
28              net_pay      DOUBLE
29          pf_employer      DOUBLE
30         esi_employer      DOUBLE
31        employer_cost      DOUBLE
32       headcount_flag      BIGINT

=======================================================
TABLE: warehouse.fact_ledger
=======================================================

                     column_name column_type
0                        line_id     VARCHAR
1                       entry_id     VARCHAR
2                       date_key      BIGINT
3                     entry_date        DATE
4                 posting_period     VARCHAR
5                 financial_year     VARCHAR
6                   account_code      BIGINT
7                          debit      DOUBLE
8                         credit      DOUBLE
9   signed_amount_debit_positive      DOUBLE
10     cost_center_department_id     VARCHAR
11                   source_type     VARCHAR
12                     source_id     VARCHAR

=======================================================
TABLE: warehouse.dim_employee
=======================================================

          column_name column_type
0        employee_key      BIGINT
1         employee_id     VARCHAR
2           full_name     VARCHAR
3              gender     VARCHAR
4       date_of_birth        DATE
5           hire_date        DATE
6           exit_date        DATE
7   employment_status     VARCHAR
8     employment_type     VARCHAR
9       department_id     VARCHAR
10            role_id     VARCHAR
11         role_title     VARCHAR
12          job_level      BIGINT
13         manager_id     VARCHAR
14      work_location     VARCHAR
15          work_mode     VARCHAR
16  highest_education     VARCHAR
17         valid_from        DATE
18           valid_to        DATE
19         is_current     VARCHAR
20      change_reason     VARCHAR

=======================================================
TABLE: warehouse.fact_attendance_monthly
=======================================================

            column_name column_type
0    attendance_fact_id     VARCHAR
1           employee_id     VARCHAR
2              date_key      BIGINT
3          employee_key      BIGINT
4         department_id     VARCHAR
5        scheduled_days      BIGINT
6          present_days      BIGINT
7              wfh_days      BIGINT
8      half_days_unpaid      BIGINT
9       paid_leave_days      BIGINT
10  unpaid_absence_days      BIGINT
11        late_arrivals      BIGINT
12     avg_hours_worked      DOUBLE
13       overtime_hours      DOUBLE
14      attendance_rate      DOUBLE
15      period_end_date        DATE

=======================================================
TABLE: warehouse.fact_leave
=======================================================

         column_name column_type
0   leave_request_id     VARCHAR
1        employee_id     VARCHAR
2       employee_key      BIGINT
3    leave_type_code     VARCHAR
4     start_date_key      BIGINT
5       end_date_key      BIGINT
6         start_date        DATE
7           end_date        DATE
8               days      BIGINT
9             status     VARCHAR
10        applied_on        DATE
11        decided_on        DATE
12       approver_id     VARCHAR
13            reason     VARCHAR

=======================================================
TABLE: warehouse.fact_invoice
=======================================================

                     column_name column_type
0                     invoice_id     VARCHAR
1                 invoice_number     VARCHAR
2                      client_id     VARCHAR
3               invoice_date_key      BIGINT
4                   invoice_date        DATE
5                       due_date        DATE
6           service_line_account      BIGINT
7                       subtotal      BIGINT
8               gst_rate_percent      BIGINT
9                     gst_amount      BIGINT
10                  total_amount      BIGINT
11                   amount_paid      BIGINT
12                   balance_due      BIGINT
13                        status     VARCHAR
14             last_payment_date        DATE
15                   days_to_pay      DOUBLE
16       days_past_due_at_cutoff      BIGINT
17       ageing_bucket_at_cutoff     VARCHAR
18  carried_in_from_prior_period     VARCHAR
19               ledger_entry_id     VARCHAR

=======================================================
TABLE: warehouse.fact_expense
=======================================================

                column_name column_type
0                expense_id     VARCHAR
1              expense_date        DATE
2          expense_date_key      BIGINT
3          category_account      BIGINT
4                 vendor_id     VARCHAR
5            bill_reference     VARCHAR
6               description     VARCHAR
7             department_id     VARCHAR
8           amount_excl_gst      BIGINT
9          gst_rate_percent      BIGINT
10               gst_amount      DOUBLE
11             total_amount      DOUBLE
12                 due_date        DATE
13                paid_date        DATE
14                   status     VARCHAR
15             payment_mode     VARCHAR
16             submitted_by     VARCHAR
17              approved_by     VARCHAR
18          ledger_entry_id     VARCHAR
19  payment_ledger_entry_id     VARCHAR

=======================================================
TABLE: warehouse.fact_task
=======================================================

             column_name column_type
0                task_id     VARCHAR
1                team_id     VARCHAR
2              sprint_id     VARCHAR
3   assignee_employee_id     VARCHAR
4              task_type     VARCHAR
5               priority     VARCHAR
6           story_points      BIGINT
7           created_date        DATE
8           started_date        DATE
9               due_date        DATE
10        completed_date        DATE
11                status     VARCHAR
12        reopened_count      BIGINT
13       cycle_time_days      DOUBLE
14  is_overdue_at_cutoff     VARCHAR
15     completed_on_time     VARCHAR

=======================================================
TABLE: warehouse.fact_attrition_risk
=======================================================

       column_name column_type
0    prediction_id     VARCHAR
1      employee_id     VARCHAR
2   as_of_date_key      BIGINT
3    department_id     VARCHAR
4       as_of_date        DATE
5   risk_score_12m      DOUBLE
6        risk_band     VARCHAR
7     top_reason_1     VARCHAR
8     top_reason_2     VARCHAR
9     top_reason_3     VARCHAR
10   model_version     VARCHAR
11      model_note     VARCHAR
12    employee_key      BIGINT

etl_run_log:

             database     schema         name
12  pulseiq_warehouse  warehouse  etl_run_log

metric_dictionary:

     database schema               name
53  source_db    raw  metric_dictionary

dq_results:

             database     schema        name
11  pulseiq_warehouse  warehouse  dq_results

In [8]:

# Inspect metric dictionary fields relevant to minimum group size
metric_dictionary = con_dq.execute("""
    SELECT *
    FROM source_db.raw.metric_dictionary
""").fetchdf()

print("Metric dictionary columns:", metric_dictionary.columns.tolist())
display(metric_dictionary)

# Inspect the source catalog's supporting tables
print("\nAvailable source tables:")
display(
    con_dq.execute("SHOW ALL TABLES").fetchdf()[
        ["database", "schema", "name"]
    ].query("database == 'source_db'")
)

# Preview key payroll and ledger fields
print("\nPayroll summary:")
display(con_dq.execute("""
    SELECT
        COUNT(*) AS row_count,
        COUNT(DISTINCT run_id) AS distinct_runs,
        MIN(period_end_date) AS first_period,
        MAX(period_end_date) AS last_period,
        ROUND(SUM(employer_cost), 2) AS total_employer_cost
    FROM warehouse.fact_payroll
""").fetchdf())

print("\nLedger summary:")
display(con_dq.execute("""
    SELECT
        COUNT(*) AS row_count,
        COUNT(DISTINCT entry_id) AS distinct_entries,
        MIN(entry_date) AS first_date,
        MAX(entry_date) AS last_date,
        COUNT(*) FILTER (
            WHERE account_code BETWEEN 5001 AND 5005
        ) AS salary_account_lines
    FROM warehouse.fact_ledger
""").fetchdf())

Metric dictionary columns: ['metric_id', 'metric_name', 'business_definition', 'formula', 'source_table', 'grain', 'time_period', 'owner_team', 'unit', 'good_direction', 'caveat', 'minimum_group_size']

,metric_id,metric_name,business_definition,formula,source_table,grain,time_period,owner_team,unit,good_direction,caveat,minimum_group_size
0,M01,Headcount,Active employees on the last day of the month (permanent and contract).,COUNT(DISTINCT employee_id) with hire_date <= month_end AND (exit_date IS NULL OR exit_date > month_end),fact_headcount_monthly / dim_employee,Department x month,Month end,HR Analytics,count,Context dependent,Excludes CEO if you compare departments only,5
1,M02,Hires,Employees whose hire_date falls in the month.,COUNT(employee_id) where hire_date in month,fact_headcount_monthly,Department x month,Month,HR Analytics,count,Context dependent,Transfers are not hires,5
2,M03,Exits,"Employees whose exit_date falls in the month (resigned, terminated or contract ended).",COUNT(employee_id) where exit_date in month,fact_headcount_monthly,Department x month,Month,HR Analytics,count,Lower is better,NaN,5
3,M04,Attrition rate (monthly),Share of people who left in the month.,Exits / headcount_start x 100,fact_headcount_monthly,Department x month,Month,HR Analytics,percent,Lower is better,Very noisy for small departments,10
4,M05,Attrition rate (rolling 12 months),Leavers in the last 12 months divided by average headcount over the same months.,"SUM(exits, 12m) / AVG(headcount_end, 12m) x 100",fact_headcount_monthly,Department x month,12 months,HR Analytics,percent,Lower is better,Use for headline reporting; monthly is too noisy,10
5,M06,Voluntary attrition rate,Same as M05 but only resignations (voluntary_exits).,"SUM(voluntary_exits, 12m) / AVG(headcount_end, 12m) x 100",fact_headcount_monthly,Department x month,12 months,HR Analytics,percent,Lower is better,NaN,10
6,M07,Gross pay,Total earnings before deductions for the month.,SUM(gross_pay),fact_payroll,Employee x month,Month,Payroll,INR,Context dependent,Includes overtime and variable pay,5
7,M08,Net pay,Take-home pay after employee deductions.,SUM(net_pay),fact_payroll,Employee x month,Month,Payroll,INR,Context dependent,NaN,5
8,M09,Payroll cost (employer cost),Full cost of employees to the company: gross pay plus employer PF and ESI.,SUM(employer_cost),fact_payroll,Employee x month,Month,Finance,INR,Lower is better when output is equal,Must reconcile with ledger accounts 5001-5005,5
9,M10,Cost per head,Average employer cost per paid employee.,SUM(employer_cost) / COUNT(DISTINCT employee_id),fact_payroll,Department x month,Month,Finance,INR,Context dependent,Part-month joiners lower the average,5
10,M11,Overtime share,How much of payroll cost is overtime pay.,SUM(overtime_pay) / SUM(employer_cost) x 100,fact_payroll,Department x month,Month,Payroll,percent,Lower is better,Only overtime-eligible roles earn overtime,5
11,M12,Variable pay share,"Bonus, incentive and award pay as a share of gross pay.",SUM(variable_pay) / SUM(gross_pay) x 100,fact_payroll,Department x month,Month,Payroll,percent,Context dependent,April bonus and quarter-end incentives create spikes,5
12,M13,Attendance rate,Days present (half day counts 0.5) divided by scheduled working days.,(SUM(present_days) + 0.5 x SUM(half_days_unpaid)) / SUM(scheduled_days),fact_attendance_monthly,Department x month,Month,HR Analytics,ratio,Higher is better,Paid leave counts as not present,5
13,M14,Late arrival rate,Late check-ins per present day.,SUM(late_arrivals) / SUM(present_days),fact_attendance_monthly,Department x month,Month,HR Analytics,ratio,Lower is better,Work-from-home days use web check-in time,5
14,M15,Leave without pay days,Unpaid absence and unpaid leave days.,SUM(lop_days) in fact_payroll,fact_payroll,Employee x month,Month,Payroll,days,Lower is better,Half-day unpaid counts 0.5,5
15,M16,Revenue,Income booked in the ledger (accounts 4001-4004).,-SUM(signed_amount) for accounts 4001-4004,fact_ledger,Account x month,Month,Finance,INR,Higher is better,Excludes GST (booked to 2200),NaN
16,M17,Net profit,Revenue minus all expenses (4xxx less 5xxx).,-SUM(signed_amount) for accounts 4xxx and 5xxx,fact_ledger,Month,Month,Finance,INR,Higher is better,Interest income (4900) is included,NaN
17,M18,Operating margin,Net profit as a share of revenue.,Net profit / Revenue x 100,fact_ledger,Month,Month,Finance,percent,Higher is better,NaN,NaN
18,M19,Payroll as % of revenue,Share of revenue consumed by payroll cost.,Payroll cost / Revenue x 100,fact_payroll + fact_ledger,Month,Month,Finance,percent,Lower is better,Use ledger payroll accounts to avoid mismatch,NaN
19,M20,Days sales outstanding (DSO),Average days to collect: receivables divided by credit sales x days.,Closing receivables / revenue incl GST (last 90 days) x 90,"fact_invoice, fact_ledger",Month,90 days,Finance,days,Lower is better,Carried-in invoices included,NaN
20,M21,Overdue receivables,Unpaid invoice balance past due date at the report date.,SUM(balance_due) where due_date < report date and status not DRAFT/CANCELLED,fact_invoice,Client x date,Point in time,Finance,INR,Lower is better,NaN,NaN
21,M22,Task completion rate,Tasks done divided by tasks planned in the sprint (cancelled tasks excluded).,COUNT(status = Done) / COUNT(status != Cancelled),fact_task,Team x sprint,Sprint,Engineering Ops,percent,Higher is better,Sample feed until the live board is ready,5 tasks
22,M23,On-time delivery rate,Done tasks completed on or before the sprint end date.,COUNT(completed_on_time = Y) / COUNT(status = Done),fact_task,Team x sprint,Sprint,Engineering Ops,percent,Higher is better,NaN,5 tasks
23,M24,Velocity,Story points completed in the sprint.,SUM(story_points) where status = Done,fact_task,Team x sprint,Sprint,Engineering Ops,points,Context dependent,Do not compare across teams,NaN
24,M25,Average cycle time,Days from start to completion for done tasks.,AVG(completed_date - started_date),fact_task,Team x sprint,Sprint,Engineering Ops,days,Lower is better,Negative values are data errors,5 tasks
25,M26,Anomaly flag rate,Share of scored records flagged by the AI anomaly service.,COUNT(flagged = Y) / COUNT(*),fact_anomaly,Source x month,Month,AI/ML,percent,Context dependent,"Flags are leads, not proof",NaN
26,M27,High-risk share,Share of employees in the High attrition-risk band.,COUNT(risk_band = High) / COUNT(*),fact_attrition_risk,Department,Point in time,AI/ML,percent,Lower is better,Show by group only; never rank named people,10
27,M28,Forecast error (MAPE),Average absolute percentage error of headcount forecasts versus actuals.,AVG(ABS(actual - forecast) / actual) x 100,fact_forecast vs fact_headcount,Department x month,Rolling,AI/ML,percent,Lower is better,Needs actuals for the forecast months,NaN

Available source tables:

     database schema                       name
25  source_db    raw  budget_payroll_dept_month
26  source_db    raw             data_contracts
27  source_db    raw            data_dictionary
28  source_db    raw                dim_account
29  source_db    raw                 dim_client
30  source_db    raw                   dim_date
31  source_db    raw             dim_department
32  source_db    raw               dim_employee
33  source_db    raw             dim_leave_type
34  source_db    raw               dim_location
35  source_db    raw                   dim_role
36  source_db    raw                 dim_sprint
37  source_db    raw                   dim_team
38  source_db    raw                 dim_vendor
39  source_db    raw          dq_checks_catalog
40  source_db    raw               fact_anomaly
41  source_db    raw    fact_attendance_monthly
42  source_db    raw        fact_attrition_risk
43  source_db    raw               fact_expense
44  source_db    raw              fact_forecast
45  source_db    raw     fact_headcount_monthly
46  source_db    raw               fact_invoice
47  source_db    raw       fact_invoice_payment
48  source_db    raw                 fact_leave
49  source_db    raw                fact_ledger
50  source_db    raw               fact_payroll
51  source_db    raw                  fact_task
52  source_db    raw                kpi_targets
53  source_db    raw          metric_dictionary

Payroll summary:

   row_count  distinct_runs first_period last_period  total_employer_cost
0       7344             18   2025-04-30  2026-09-30         8.619974e+08

Ledger summary:

   row_count  distinct_entries first_date  last_date  salary_account_lines
0       6784              2524 2025-04-01 2026-09-30                   557

In [9]:

# PQ-03: Initial data-quality checks (DQ-C01 to DQ-C04)

dq01 = con_dq.execute("""
    WITH payroll_monthly AS (
        SELECT
            DATE_TRUNC('month', period_end_date)::DATE AS month,
            SUM(employer_cost) AS payroll_cost
        FROM warehouse.fact_payroll
        GROUP BY 1
    ),
    ledger_monthly AS (
        SELECT
            DATE_TRUNC('month', entry_date)::DATE AS month,
            SUM(debit - credit) AS ledger_cost
        FROM warehouse.fact_ledger
        WHERE account_code BETWEEN 5001 AND 5005
        GROUP BY 1
    )
    SELECT
        COALESCE(p.month, l.month) AS month,
        p.payroll_cost,
        l.ledger_cost,
        p.payroll_cost - l.ledger_cost AS difference
    FROM payroll_monthly p
    FULL OUTER JOIN ledger_monthly l USING (month)
    WHERE p.month IS NULL
       OR l.month IS NULL
       OR ABS(p.payroll_cost - l.ledger_cost) > 0.01
    ORDER BY month
""").fetchdf()

dq02 = con_dq.execute("""
    SELECT
        entry_id,
        SUM(debit) AS total_debit,
        SUM(credit) AS total_credit,
        ABS(SUM(debit) - SUM(credit)) AS difference
    FROM warehouse.fact_ledger
    GROUP BY entry_id
    HAVING ABS(SUM(debit) - SUM(credit)) > 0.005
""").fetchdf()

dq03 = con_dq.execute("""
    SELECT
        employee_id,
        run_id,
        COUNT(*) AS row_count
    FROM warehouse.fact_payroll
    GROUP BY employee_id, run_id
    HAVING COUNT(*) > 1
""").fetchdf()

dq04 = con_dq.execute("""
    SELECT f.payroll_item_id, f.employee_id, f.run_id
    FROM warehouse.fact_payroll f
    LEFT JOIN warehouse.dim_employee d
        ON f.employee_id = d.employee_id
    WHERE d.employee_id IS NULL
""").fetchdf()

initial_results = {
    "DQ-C01": dq01,
    "DQ-C02": dq02,
    "DQ-C03": dq03,
    "DQ-C04": dq04,
}

for check_id, bad_rows in initial_results.items():
    print(f"\n{check_id}: {len(bad_rows)} failing result row(s)")
    display(bad_rows.head(10))

DQ-C01: 5 failing result row(s)

       month  payroll_cost  ledger_cost  difference
0 2025-05-01   40717628.17  40655815.02    61813.15
1 2025-12-01   47420813.68  47322486.26    98327.42
2 2026-02-01   44198850.60  44044038.71   154811.89
3 2026-04-01   62264040.50  62168025.50    96015.00
4 2026-06-01   54664233.35  54682683.35   -18450.00

DQ-C02: 0 failing result row(s)

Empty DataFrame
Columns: [entry_id, total_debit, total_credit, difference]
Index: []

DQ-C03: 2 failing result row(s)

  employee_id      run_id  row_count
0    EMP-0194  PR-2026-02          2
1    EMP-0598  PR-2025-05          2

DQ-C04: 2 failing result row(s)

  payroll_item_id employee_id      run_id
0        PI-X0003    EMP-9001  PR-2026-04
1        PI-X0004    EMP-9002  PR-2025-12

In [10]:

# Investigate salary-related ledger postings
ledger_sign_check = con_dq.execute("""
    SELECT
        account_code,
        source_type,
        COUNT(*) AS line_count,
        ROUND(SUM(debit), 2) AS total_debit,
        ROUND(SUM(credit), 2) AS total_credit,
        ROUND(SUM(debit - credit), 2) AS debit_minus_credit,
        ROUND(SUM(signed_amount_debit_positive), 2)
            AS signed_amount_total
    FROM warehouse.fact_ledger
    WHERE account_code BETWEEN 5001 AND 5005
    GROUP BY account_code, source_type
    ORDER BY account_code, source_type
""").fetchdf()

display(ledger_sign_check)

print("\nMonthly reconciliation using the signed amount column:")
display(con_dq.execute("""
    WITH payroll_monthly AS (
        SELECT
            DATE_TRUNC('month', period_end_date)::DATE AS month,
            SUM(employer_cost) AS payroll_cost
        FROM warehouse.fact_payroll
        GROUP BY 1
    ),
    ledger_monthly AS (
        SELECT
            DATE_TRUNC('month', entry_date)::DATE AS month,
            SUM(signed_amount_debit_positive) AS ledger_cost
        FROM warehouse.fact_ledger
        WHERE account_code BETWEEN 5001 AND 5005
        GROUP BY 1
    )
    SELECT
        COALESCE(p.month, l.month) AS month,
        p.payroll_cost,
        l.ledger_cost,
        p.payroll_cost - l.ledger_cost AS difference
    FROM payroll_monthly p
    FULL OUTER JOIN ledger_monthly l USING (month)
    WHERE p.month IS NULL
       OR l.month IS NULL
       OR ABS(p.payroll_cost - l.ledger_cost) > 0.01
    ORDER BY month
""").fetchdf())

,account_code,source_type,line_count,total_debit,total_credit,debit_minus_credit,signed_amount_total
0,5001,PAYROLL_RUN,198,7.869242e+08,0.0,7.869242e+08,7.869242e+08
1,5002,PAYROLL_RUN,72,3.024619e+06,0.0,3.024619e+06,3.024619e+06
2,5003,PAYROLL_RUN,71,5.969659e+07,0.0,5.969659e+07,5.969659e+07
3,5004,PAYROLL_RUN,198,1.188891e+07,0.0,1.188891e+07,1.188891e+07
4,5005,PAYROLL_RUN,18,7.052200e+04,0.0,7.052200e+04,7.052200e+04

Monthly reconciliation using the signed amount column:

       month  payroll_cost  ledger_cost  difference
0 2025-05-01   40717628.17  40655815.02    61813.15
1 2025-12-01   47420813.68  47322486.26    98327.42
2 2026-02-01   44198850.60  44044038.71   154811.89
3 2026-04-01   62264040.50  62168025.50    96015.00
4 2026-06-01   54664233.35  54682683.35   -18450.00

In [11]:

# Inspect payroll and salary-related ledger totals by month and account
display(con_dq.execute("""
    WITH payroll_monthly AS (
        SELECT
            DATE_TRUNC('month', period_end_date)::DATE AS month,
            SUM(employer_cost) AS payroll_cost
        FROM warehouse.fact_payroll
        GROUP BY 1
    ),
    ledger_monthly AS (
        SELECT
            DATE_TRUNC('month', entry_date)::DATE AS month,
            account_code,
            SUM(signed_amount_debit_positive) AS account_cost
        FROM warehouse.fact_ledger
        WHERE account_code BETWEEN 5001 AND 5005
        GROUP BY 1, 2
    )
    SELECT
        l.month,
        l.account_code,
        ROUND(l.account_cost, 2) AS account_cost,
        ROUND(p.payroll_cost, 2) AS payroll_cost
    FROM ledger_monthly l
    LEFT JOIN payroll_monthly p USING (month)
    WHERE l.month IN (
        DATE '2025-05-01',
        DATE '2025-12-01',
        DATE '2026-02-01',
        DATE '2026-04-01',
        DATE '2026-06-01'
    )
    ORDER BY l.month, l.account_code
""").fetchdf())

        month  account_code  account_cost  payroll_cost
0  2025-05-01          5001   39852272.98   40717628.17
1  2025-05-01          5002     149402.81   40717628.17
2  2025-05-01          5003      35000.00   40717628.17
3  2025-05-01          5004     615802.55   40717628.17
4  2025-05-01          5005       3336.68   40717628.17
5  2025-12-01          5001   42163177.69   47420813.68
6  2025-12-01          5002     233769.61   47420813.68
7  2025-12-01          5003    4271184.03   47420813.68
8  2025-12-01          5004     649164.15   47420813.68
9  2025-12-01          5005       5190.78   47420813.68
10 2026-02-01          5001   43192244.43   44198850.60
11 2026-02-01          5002     154102.21   44198850.60
12 2026-02-01          5003      20000.00   44198850.60
13 2026-02-01          5004     672338.35   44198850.60
14 2026-02-01          5005       5353.72   44198850.60
15 2026-04-01          5001   47061105.91   62264040.50
16 2026-04-01          5002     165578.79   62264040.50
17 2026-04-01          5003   14259540.22   62264040.50
18 2026-04-01          5004     679229.62   62264040.50
19 2026-04-01          5005       2570.96   62264040.50
20 2026-06-01          5001   47648234.08   54664233.35
21 2026-06-01          5002     166654.42   54664233.35
22 2026-06-01          5003    6175425.07   54664233.35
23 2026-06-01          5004     689715.75   54664233.35
24 2026-06-01          5005       2654.03   54664233.35

In [12]:

# PQ-03: Data-quality checks DQ-C05 to DQ-C08

# DQ-C05: Attendance after employee exit
dq05 = con_dq.execute("""
    SELECT
        a.attendance_fact_id,
        a.employee_id,
        a.period_end_date,
        d.exit_date
    FROM warehouse.fact_attendance_monthly a
    JOIN warehouse.dim_employee d
        ON a.employee_id = d.employee_id
       AND a.employee_key = d.employee_key
    WHERE d.exit_date IS NOT NULL
      AND a.period_end_date > LAST_DAY(d.exit_date)
""").fetchdf()

# DQ-C06: Compare unpaid absence days with payroll LOP days
dq06 = con_dq.execute("""
    WITH attendance_monthly AS (
        SELECT
            employee_id,
            DATE_TRUNC('month', period_end_date)::DATE AS month,
            SUM(unpaid_absence_days) AS unpaid_absence_days
        FROM warehouse.fact_attendance_monthly
        GROUP BY 1, 2
    ),
    payroll_monthly AS (
        SELECT
            employee_id,
            DATE_TRUNC('month', period_end_date)::DATE AS month,
            SUM(lop_days) AS lop_days
        FROM warehouse.fact_payroll
        GROUP BY 1, 2
    )
    SELECT
        COALESCE(a.employee_id, p.employee_id) AS employee_id,
        COALESCE(a.month, p.month) AS month,
        a.unpaid_absence_days,
        p.lop_days,
        ABS(
            COALESCE(a.unpaid_absence_days, 0)
            - COALESCE(p.lop_days, 0)
        ) AS difference_days
    FROM attendance_monthly a
    FULL OUTER JOIN payroll_monthly p
        ON a.employee_id = p.employee_id
       AND a.month = p.month
    WHERE ABS(
        COALESCE(a.unpaid_absence_days, 0)
        - COALESCE(p.lop_days, 0)
    ) > 0.5
""").fetchdf()

# DQ-C07: Invoice arithmetic
dq07 = con_dq.execute("""
    SELECT
        invoice_id,
        total_amount,
        amount_paid,
        balance_due
    FROM warehouse.fact_invoice
    WHERE amount_paid > total_amount
       OR balance_due < 0
""").fetchdf()

# DQ-C08: Expense arithmetic
dq08 = con_dq.execute("""
    SELECT
        expense_id,
        amount_excl_gst,
        gst_amount,
        total_amount,
        total_amount - (amount_excl_gst + gst_amount) AS difference
    FROM warehouse.fact_expense
    WHERE ABS(
        total_amount - (amount_excl_gst + gst_amount)
    ) > 0.01
""").fetchdf()

checks_05_08 = {
    "DQ-C05": dq05,
    "DQ-C06": dq06,
    "DQ-C07": dq07,
    "DQ-C08": dq08,
}

for check_id, bad_rows in checks_05_08.items():
    print(f"\n{check_id}: {len(bad_rows)} failing result row(s)")
    display(bad_rows.head(10))

DQ-C05: 4 failing result row(s)

  attendance_fact_id employee_id period_end_date  exit_date
0           FA-X0001    EMP-0476      2026-03-31 2026-02-27
1           FA-X0002    EMP-0183      2026-03-31 2026-02-17
2           FA-X0003    EMP-0540      2025-11-30 2025-10-28
3           FA-X0004    EMP-0490      2025-12-31 2025-11-17

DQ-C06: 43 failing result row(s)

  employee_id      month  unpaid_absence_days  lop_days  difference_days
0    EMP-0420 2026-05-01                  0.0       1.0              1.0
1    EMP-0188 2025-04-01                  0.0       1.0              1.0
2    EMP-0155 2025-07-01                  0.0       1.0              1.0
3    EMP-0111 2026-07-01                  2.0       3.0              1.0
4    EMP-0261 2026-07-01                  4.0       5.0              1.0
5    EMP-0100 2025-04-01                  0.0       1.0              1.0
6    EMP-0598 2025-05-01                  2.0       4.0              2.0
7    EMP-0592 2025-09-01                  0.0       1.0              1.0
8    EMP-0019 2026-01-01                  0.0       1.0              1.0
9    EMP-0087 2026-01-01                  0.0       1.0              1.0

DQ-C07: 1 failing result row(s)

  invoice_id  total_amount  amount_paid  balance_due
0  INV-00385       1049728      1049828         -100

DQ-C08: 1 failing result row(s)

  expense_id  amount_excl_gst  gst_amount  total_amount  difference
0  EXP-00371           164090     19690.8      184280.8       500.0

In [13]:

# PQ-03: Data-quality checks DQ-C09 to DQ-C12

# DQ-C09: Task dates sensible
dq09 = con_dq.execute("""
    SELECT
        task_id,
        status,
        started_date,
        completed_date
    FROM warehouse.fact_task
    WHERE (
        started_date IS NOT NULL
        AND completed_date IS NOT NULL
        AND completed_date < started_date
    )
    OR (
        LOWER(status) = 'done'
        AND completed_date IS NULL
    )
""").fetchdf()

# DQ-C10: Leave dates sensible
dq10 = con_dq.execute("""
    SELECT
        leave_request_id,
        start_date,
        end_date,
        status
    FROM warehouse.fact_leave
    WHERE start_date IS NOT NULL
      AND end_date IS NOT NULL
      AND end_date < start_date
""").fetchdf()

# DQ-C11: AI prediction freshness
dq11 = con_dq.execute("""
    SELECT
        prediction_id,
        as_of_date,
        (SELECT MAX(as_of_date)
         FROM warehouse.fact_attrition_risk) AS latest_as_of_date
    FROM warehouse.fact_attrition_risk
    WHERE as_of_date < (
        SELECT MAX(as_of_date)
        FROM warehouse.fact_attrition_risk
    ) - INTERVAL 7 DAYS
""").fetchdf()

# DQ-C12: Employee dimension history overlaps
dq12 = con_dq.execute("""
    SELECT
        a.employee_id,
        a.employee_key AS earlier_key,
        a.valid_from AS earlier_valid_from,
        a.valid_to AS earlier_valid_to,
        b.employee_key AS later_key,
        b.valid_from AS later_valid_from,
        b.valid_to AS later_valid_to
    FROM warehouse.dim_employee a
    JOIN warehouse.dim_employee b
      ON a.employee_id = b.employee_id
     AND a.employee_key < b.employee_key
     AND a.valid_from <= b.valid_to
     AND b.valid_from <= a.valid_to
""").fetchdf()

checks_09_12 = {
    "DQ-C09": dq09,
    "DQ-C10": dq10,
    "DQ-C11": dq11,
    "DQ-C12": dq12,
}

for check_id, bad_rows in checks_09_12.items():
    print(f"\n{check_id}: {len(bad_rows)} failing result row(s)")
    display(bad_rows.head(10))

DQ-C09: 20 failing result row(s)

      task_id status started_date completed_date
0  TASK-02741   Done   2025-05-22     2025-05-19
1  TASK-02895   Done   2025-06-03     2025-06-02
2  TASK-03925   Done   2025-06-16            NaT
3  TASK-06380   Done   2025-08-04     2025-08-03
4  TASK-07633   Done   2025-08-26     2025-08-22
5  TASK-09527   Done   2025-09-24     2025-09-20
6  TASK-10799   Done   2025-10-21     2025-10-17
7  TASK-13041   Done   2025-12-03            NaT
8  TASK-16893   Done   2026-02-25            NaT
9  TASK-17195   Done   2026-03-03            NaT

DQ-C10: 2 failing result row(s)

  leave_request_id start_date   end_date    status
0        LR-000025 2026-02-20 2026-02-19  Rejected
1        LR-002286 2026-03-24 2026-03-23  Approved

DQ-C11: 5 failing result row(s)

  prediction_id as_of_date latest_as_of_date
0       AR-0119 2026-03-31        2026-09-30
1       AR-0221 2026-03-31        2026-09-30
2       AR-0238 2026-03-31        2026-09-30
3       AR-0278 2026-03-31        2026-09-30
4       AR-0279 2026-03-31        2026-09-30

DQ-C12: 1 failing result row(s)

,employee_id,earlier_key,earlier_valid_from,earlier_valid_to,later_key,later_valid_from,later_valid_to
0,EMP-0001,100000,2012-01-19,2012-05-12,100001,2012-05-03,2015-05-13

In [14]:

# PQ-03: DQ-C13 and DQ-C14

# DQ-C13: Pipeline freshness
# No etl_run_log table exists, so this check cannot be evaluated yet.
dq13 = pd.DataFrame([{
    "check_id": "DQ-C13",
    "status": "BLOCKED",
    "reason": "etl_run_log table is not available",
    "failing_rows": None
}])

print("DQ-C13 — Pipeline freshness")
display(dq13)

# DQ-C14: Minimum group size
# Evaluate employee counts by department and month for metrics
# with a numeric minimum_group_size.
metric_sizes = con_dq.execute("""
    SELECT
        metric_id,
        metric_name,
        source_table,
        grain,
        minimum_group_size
    FROM source_db.raw.metric_dictionary
    WHERE TRY_CAST(minimum_group_size AS INTEGER) IS NOT NULL
""").fetchdf()

print("Metrics with a defined minimum group size:")
display(metric_sizes)

# Demonstrate the check on employee-level payroll aggregates.
# A department-month with fewer than 5 distinct employees is flagged.
dq14 = con_dq.execute("""
    SELECT
        DATE_TRUNC('month', p.period_end_date)::DATE AS month,
        p.department_id,
        COUNT(DISTINCT p.employee_id) AS employee_count,
        5 AS minimum_group_size
    FROM warehouse.fact_payroll p
    GROUP BY 1, 2
    HAVING COUNT(DISTINCT p.employee_id) < 5
    ORDER BY month, department_id
""").fetchdf()

print("\nDQ-C14 — Small department-month groups:")
print("Failing groups:", len(dq14))
display(dq14.head(20))

DQ-C13 — Pipeline freshness

  check_id   status                              reason failing_rows
0   DQ-C13  BLOCKED  etl_run_log table is not available         None

Metrics with a defined minimum group size:

,metric_id,metric_name,source_table,grain,minimum_group_size
0,M01,Headcount,fact_headcount_monthly / dim_employee,Department x month,5
1,M02,Hires,fact_headcount_monthly,Department x month,5
2,M03,Exits,fact_headcount_monthly,Department x month,5
3,M04,Attrition rate (monthly),fact_headcount_monthly,Department x month,10
4,M05,Attrition rate (rolling 12 months),fact_headcount_monthly,Department x month,10
5,M06,Voluntary attrition rate,fact_headcount_monthly,Department x month,10
6,M07,Gross pay,fact_payroll,Employee x month,5
7,M08,Net pay,fact_payroll,Employee x month,5
8,M09,Payroll cost (employer cost),fact_payroll,Employee x month,5
9,M10,Cost per head,fact_payroll,Department x month,5
10,M11,Overtime share,fact_payroll,Department x month,5
11,M12,Variable pay share,fact_payroll,Department x month,5
12,M13,Attendance rate,fact_attendance_monthly,Department x month,5
13,M14,Late arrival rate,fact_attendance_monthly,Department x month,5
14,M15,Leave without pay days,fact_payroll,Employee x month,5
15,M27,High-risk share,fact_attrition_risk,Department,10

DQ-C14 — Small department-month groups:
Failing groups: 18

        month department_id  employee_count  minimum_group_size
0  2025-04-01           D00               1                   5
1  2025-05-01           D00               1                   5
2  2025-06-01           D00               1                   5
3  2025-07-01           D00               1                   5
4  2025-08-01           D00               1                   5
5  2025-09-01           D00               1                   5
6  2025-10-01           D00               1                   5
7  2025-11-01           D00               1                   5
8  2025-12-01           D00               1                   5
9  2026-01-01           D00               1                   5
10 2026-02-01           D00               1                   5
11 2026-03-01           D00               1                   5
12 2026-04-01           D00               1                   5
13 2026-05-01           D00               1                   5
14 2026-06-01           D00               1                   5
15 2026-07-01           D00               1                   5
16 2026-08-01           D00               1                   5
17 2026-09-01           D00               1                   5

In [15]:

# PQ-03: Consolidate the 14 checks into a summary

check_frames = {
    "DQ-C01": dq01,
    "DQ-C02": dq02,
    "DQ-C03": dq03,
    "DQ-C04": dq04,
    "DQ-C05": dq05,
    "DQ-C06": dq06,
    "DQ-C07": dq07,
    "DQ-C08": dq08,
    "DQ-C09": dq09,
    "DQ-C10": dq10,
    "DQ-C11": dq11,
    "DQ-C12": dq12,
    "DQ-C13": dq13,
    "DQ-C14": dq14,
}

# Map each result to the catalog's severity and name
catalog_lookup = dq_catalog.set_index("check_id")

summary_rows = []

for check_id, bad_rows in check_frames.items():
    catalog_row = catalog_lookup.loc[check_id]

    if check_id == "DQ-C13":
        status = "BLOCKED"
        failing_rows = None
        reason = "etl_run_log table is unavailable"
    else:
        failing_rows = len(bad_rows)
        status = "PASS" if failing_rows == 0 else "FAIL"
        reason = (
            "No failing rows returned"
            if status == "PASS"
            else f"{failing_rows} failing result row(s)"
        )

    summary_rows.append({
        "check_id": check_id,
        "check_name": catalog_row["check_name"],
        "severity": catalog_row["severity"],
        "status": status,
        "failing_rows": failing_rows,
        "reason": reason,
    })

dq_summary = pd.DataFrame(summary_rows)

print("Check summary:")
display(dq_summary)

print("\nStatus counts:")
display(
    dq_summary.groupby("status", dropna=False)
    .size()
    .reset_index(name="check_count")
)

print("\nSeverity and status:")
display(
    dq_summary.groupby(["severity", "status"], dropna=False)
    .size()
    .reset_index(name="check_count")
)

Check summary:

,check_id,check_name,severity,status,failing_rows,reason
0,DQ-C01,Payroll equals ledger,Critical,FAIL,5.0,5 failing result row(s)
1,DQ-C02,Ledger balanced,Critical,PASS,0.0,No failing rows returned
2,DQ-C03,Unique payroll rows,Critical,FAIL,2.0,2 failing result row(s)
3,DQ-C04,No orphan employees,Critical,FAIL,2.0,2 failing result row(s)
4,DQ-C05,No attendance after exit,Warning,FAIL,4.0,4 failing result row(s)
5,DQ-C06,Unpaid leave deducted,Warning,FAIL,43.0,43 failing result row(s)
6,DQ-C07,Invoice arithmetic,Warning,FAIL,1.0,1 failing result row(s)
7,DQ-C08,Expense arithmetic,Warning,FAIL,1.0,1 failing result row(s)
8,DQ-C09,Task dates sensible,Warning,FAIL,20.0,20 failing result row(s)
9,DQ-C10,Leave dates sensible,Warning,FAIL,2.0,2 failing result row(s)
10,DQ-C11,AI feeds are fresh,Warning,FAIL,5.0,5 failing result row(s)
11,DQ-C12,Dimension history does not overlap,Critical,FAIL,1.0,1 failing result row(s)
12,DQ-C13,Pipeline freshness,Critical,BLOCKED,NaN,etl_run_log table is unavailable
13,DQ-C14,Minimum group size,Critical,FAIL,18.0,18 failing result row(s)

Status counts:

    status  check_count
0  BLOCKED            1
1     FAIL           12
2     PASS            1

Severity and status:

   severity   status  check_count
0  Critical  BLOCKED            1
1  Critical     FAIL            5
2  Critical     PASS            1
3   Warning     FAIL            7

In [16]:

# PQ-03: Persist the consolidated check summary in the warehouse

from datetime import datetime, timezone

dq_results_to_save = dq_summary.copy()
dq_results_to_save["run_timestamp"] = datetime.now(timezone.utc)
dq_results_to_save["failing_rows"] = (
    dq_results_to_save["failing_rows"].astype("Int64")
)

# Create or replace only the PQ-03 results table in the warehouse
con_dq.register("dq_summary_to_save", dq_results_to_save)

con_dq.execute("""
    CREATE OR REPLACE TABLE warehouse.dq_results AS
    SELECT *
    FROM dq_summary_to_save
""")

con_dq.unregister("dq_summary_to_save")

print("DQ results table saved.")

display(con_dq.execute("""
    SELECT check_id, check_name, severity, status,
           failing_rows, run_timestamp
    FROM warehouse.dq_results
    ORDER BY check_id
""").fetchdf())

DQ results table saved.

,check_id,check_name,severity,status,failing_rows,run_timestamp
0,DQ-C01,Payroll equals ledger,Critical,FAIL,5,2026-10-21 13:03:03.511298+05:30
1,DQ-C02,Ledger balanced,Critical,PASS,0,2026-10-21 13:03:03.511298+05:30
2,DQ-C03,Unique payroll rows,Critical,FAIL,2,2026-10-21 13:03:03.511298+05:30
3,DQ-C04,No orphan employees,Critical,FAIL,2,2026-10-21 13:03:03.511298+05:30
4,DQ-C05,No attendance after exit,Warning,FAIL,4,2026-10-21 13:03:03.511298+05:30
5,DQ-C06,Unpaid leave deducted,Warning,FAIL,43,2026-10-21 13:03:03.511298+05:30
6,DQ-C07,Invoice arithmetic,Warning,FAIL,1,2026-10-21 13:03:03.511298+05:30
7,DQ-C08,Expense arithmetic,Warning,FAIL,1,2026-10-21 13:03:03.511298+05:30
8,DQ-C09,Task dates sensible,Warning,FAIL,20,2026-10-21 13:03:03.511298+05:30
9,DQ-C10,Leave dates sensible,Warning,FAIL,2,2026-10-21 13:03:03.511298+05:30
10,DQ-C11,AI feeds are fresh,Warning,FAIL,5,2026-10-21 13:03:03.511298+05:30
11,DQ-C12,Dimension history does not overlap,Critical,FAIL,1,2026-10-21 13:03:03.511298+05:30
12,DQ-C13,Pipeline freshness,Critical,BLOCKED,<NA>,2026-10-21 13:03:03.511298+05:30
13,DQ-C14,Minimum group size,Critical,FAIL,18,2026-10-21 13:03:03.511298+05:30

In [17]:

# Inspect departments and the D00 group
print("Department dimension:")
display(con_dq.execute("""
    SELECT *
    FROM warehouse.dim_department
    ORDER BY department_id
""").fetchdf())

print("\nEmployee counts by department:")
display(con_dq.execute("""
    SELECT
        department_id,
        COUNT(DISTINCT employee_id) AS employee_count,
        COUNT(*) AS dimension_rows
    FROM warehouse.dim_employee
    GROUP BY department_id
    ORDER BY department_id
""").fetchdf())

print("\nD00 employee details:")
display(con_dq.execute("""
    SELECT
        employee_id,
        full_name,
        role_title,
        employment_status,
        is_current,
        exit_date
    FROM warehouse.dim_employee
    WHERE department_id = 'D00'
    ORDER BY employee_id
""").fetchdf())

Department dimension:

,department_id,department_name,cost_center,description,is_leadership
0,D00,Executive Office,CC-000,Leadership & strategy,Y
1,D01,Engineering,CC-100,"Product engineering, QA and DevOps",N
2,D02,Product & Design,CC-200,Product management and UX design,N
3,D03,Data & AI,CC-300,"Data engineering, analytics and machine learning",N
4,D04,Sales,CC-400,Enterprise and mid-market sales,N
5,D05,Marketing,CC-500,"Brand, content and digital marketing",N
6,D06,Customer Support,CC-600,Customer success and support desk,N
7,D07,Human Resources,CC-700,"Talent, people operations and payroll",N
8,D08,Finance & Accounts,CC-800,"Accounting, controls and reporting",N
9,D09,Operations & IT,CC-900,"Facilities, IT systems and operations",N
10,D10,Legal & Compliance,CC-950,"Contracts, policy and statutory compliance",N

Employee counts by department:

   department_id  employee_count  dimension_rows
0            D00               1               1
1            D01             272             576
2            D02              40              88
3            D03              81             178
4            D04              90             186
5            D05              29              54
6            D06             108             198
7            D07              33              86
8            D08              29              61
9            D09              62             129
10           D10              18              49

D00 employee details:

,employee_id,full_name,role_title,employment_status,is_current,exit_date
0,EMP-0006,Tejas Chowdhury,Chief Executive Officer,Active,Y,NaT

In [18]:

# DQ-C14: Apply minimum group size and identify suppressed groups

dq14_refined = con_dq.execute("""
    WITH department_month AS (
        SELECT
            DATE_TRUNC('month', p.period_end_date)::DATE AS month,
            p.department_id,
            COUNT(DISTINCT p.employee_id) AS employee_count
        FROM warehouse.fact_payroll p
        GROUP BY 1, 2
    )
    SELECT
        dm.month,
        dm.department_id,
        d.department_name,
        d.is_leadership,
        dm.employee_count,
        CASE
            WHEN dm.employee_count < 5 THEN 'SUPPRESS'
            ELSE 'PASS'
        END AS privacy_status
    FROM department_month dm
    LEFT JOIN warehouse.dim_department d
        ON dm.department_id = d.department_id
    ORDER BY dm.month, dm.department_id
""").fetchdf()

print("Privacy status counts:")
display(
    dq14_refined.groupby("privacy_status")
    .size()
    .reset_index(name="group_count")
)

print("\nGroups requiring suppression:")
display(
    dq14_refined[
        dq14_refined["privacy_status"] == "SUPPRESS"
    ]
)

Privacy status counts:

  privacy_status  group_count
0           PASS          180
1       SUPPRESS           18

Groups requiring suppression:

,month,department_id,department_name,is_leadership,employee_count,privacy_status
0,2025-04-01,D00,Executive Office,Y,1,SUPPRESS
11,2025-05-01,D00,Executive Office,Y,1,SUPPRESS
22,2025-06-01,D00,Executive Office,Y,1,SUPPRESS
33,2025-07-01,D00,Executive Office,Y,1,SUPPRESS
44,2025-08-01,D00,Executive Office,Y,1,SUPPRESS
55,2025-09-01,D00,Executive Office,Y,1,SUPPRESS
66,2025-10-01,D00,Executive Office,Y,1,SUPPRESS
77,2025-11-01,D00,Executive Office,Y,1,SUPPRESS
88,2025-12-01,D00,Executive Office,Y,1,SUPPRESS
99,2026-01-01,D00,Executive Office,Y,1,SUPPRESS
110,2026-02-01,D00,Executive Office,Y,1,SUPPRESS
121,2026-03-01,D00,Executive Office,Y,1,SUPPRESS
132,2026-04-01,D00,Executive Office,Y,1,SUPPRESS
143,2026-05-01,D00,Executive Office,Y,1,SUPPRESS
154,2026-06-01,D00,Executive Office,Y,1,SUPPRESS
165,2026-07-01,D00,Executive Office,Y,1,SUPPRESS
176,2026-08-01,D00,Executive Office,Y,1,SUPPRESS
187,2026-09-01,D00,Executive Office,Y,1,SUPPRESS

In [19]:

# DQ-C06: Classify attendance/payroll mismatches

dq06_review = con_dq.execute("""
    WITH attendance_monthly AS (
        SELECT
            employee_id,
            DATE_TRUNC('month', period_end_date)::DATE AS month,
            SUM(unpaid_absence_days) AS unpaid_absence_days
        FROM warehouse.fact_attendance_monthly
        GROUP BY 1, 2
    ),
    payroll_monthly AS (
        SELECT
            employee_id,
            DATE_TRUNC('month', period_end_date)::DATE AS month,
            SUM(lop_days) AS lop_days
        FROM warehouse.fact_payroll
        GROUP BY 1, 2
    )
    SELECT
        COALESCE(a.employee_id, p.employee_id) AS employee_id,
        COALESCE(a.month, p.month) AS month,
        a.unpaid_absence_days,
        p.lop_days,
        CASE
            WHEN a.employee_id IS NULL THEN 'MISSING_ATTENDANCE'
            WHEN p.employee_id IS NULL THEN 'MISSING_PAYROLL'
            WHEN ABS(a.unpaid_absence_days - p.lop_days) <= 0.5
                THEN 'WITHIN_TOLERANCE'
            ELSE 'DAY_MISMATCH'
        END AS exception_type
    FROM attendance_monthly a
    FULL OUTER JOIN payroll_monthly p
        ON a.employee_id = p.employee_id
       AND a.month = p.month
    WHERE a.employee_id IS NULL
       OR p.employee_id IS NULL
       OR ABS(
            COALESCE(a.unpaid_absence_days, 0)
            - COALESCE(p.lop_days, 0)
       ) > 0.5
    ORDER BY month, employee_id
""").fetchdf()

print("Exception classification:")
display(
    dq06_review.groupby("exception_type")
    .size()
    .reset_index(name="record_count")
)

print("\nSample exceptions:")
display(dq06_review.head(20))

Exception classification:

       exception_type  record_count
0        DAY_MISMATCH            41
1  MISSING_ATTENDANCE             3
2     MISSING_PAYROLL             4

Sample exceptions:

   employee_id      month  unpaid_absence_days  lop_days   exception_type
0     EMP-0100 2025-04-01                  0.0       1.0     DAY_MISMATCH
1     EMP-0188 2025-04-01                  0.0       1.0     DAY_MISMATCH
2     EMP-0501 2025-04-01                  0.0       1.0     DAY_MISMATCH
3     EMP-0578 2025-05-01                  1.0       2.5     DAY_MISMATCH
4     EMP-0598 2025-05-01                  2.0       4.0     DAY_MISMATCH
5     EMP-0472 2025-06-01                  0.0       1.0     DAY_MISMATCH
6     EMP-0155 2025-07-01                  0.0       1.0     DAY_MISMATCH
7     EMP-0428 2025-07-01                  0.0       1.0     DAY_MISMATCH
8     EMP-0349 2025-08-01                  0.0       1.0     DAY_MISMATCH
9     EMP-0034 2025-09-01                  0.0       1.0     DAY_MISMATCH
10    EMP-0199 2025-09-01                  0.0       1.0     DAY_MISMATCH
11    EMP-0434 2025-09-01                  0.0       1.0     DAY_MISMATCH
12    EMP-0497 2025-09-01                  0.0       1.0     DAY_MISMATCH
13    EMP-0578 2025-09-01                  0.0       1.0     DAY_MISMATCH
14    EMP-0592 2025-09-01                  0.0       1.0     DAY_MISMATCH
15    EMP-0423 2025-11-01                  0.0       1.0     DAY_MISMATCH
16    EMP-0540 2025-11-01                  0.0       NaN  MISSING_PAYROLL
17    EMP-0578 2025-11-01                  0.0       1.0     DAY_MISMATCH
18    EMP-0096 2025-12-01                  0.0       1.0     DAY_MISMATCH
19    EMP-0490 2025-12-01                  1.0       NaN  MISSING_PAYROLL

In [20]:

# Refine DQ-C06 exception counts
dq06_exception_counts = (
    dq06_review.groupby("exception_type")
    .size()
    .to_dict()
)

dq06_total_exceptions = len(dq06_review)

print("DQ-C06 total exceptions:", dq06_total_exceptions)
print("Breakdown:", dq06_exception_counts)

# Update the summary row in memory
dq_summary.loc[dq_summary["check_id"] == "DQ-C06", "failing_rows"] = (
    dq06_total_exceptions
)
dq_summary.loc[dq_summary["check_id"] == "DQ-C06", "status"] = "FAIL"
dq_summary.loc[dq_summary["check_id"] == "DQ-C06", "reason"] = (
    f"{dq06_exception_counts.get('DAY_MISMATCH', 0)} day mismatches; "
    f"{dq06_exception_counts.get('MISSING_ATTENDANCE', 0)} missing attendance; "
    f"{dq06_exception_counts.get('MISSING_PAYROLL', 0)} missing payroll"
)

display(
    dq_summary[dq_summary["check_id"] == "DQ-C06"]
)

print("\nException breakdown for the report:")
display(
    pd.DataFrame([
        {"exception_type": key, "record_count": value}
        for key, value in dq06_exception_counts.items()
    ])
)

DQ-C06 total exceptions: 48
Breakdown: {'DAY_MISMATCH': 41, 'MISSING_ATTENDANCE': 3, 'MISSING_PAYROLL': 4}

,check_id,check_name,severity,status,failing_rows,reason
5,DQ-C06,Unpaid leave deducted,Warning,FAIL,48.0,41 day mismatches; 3 missing attendance; 4 missing payroll

Exception breakdown for the report:

       exception_type  record_count
0        DAY_MISMATCH            41
1  MISSING_ATTENDANCE             3
2     MISSING_PAYROLL             4

In [21]:

# Persist the revised PQ-03 summary
dq_results_to_save = dq_summary.copy()
dq_results_to_save["run_timestamp"] = datetime.now(timezone.utc)
dq_results_to_save["failing_rows"] = (
    dq_results_to_save["failing_rows"].astype("Int64")
)

con_dq.register("dq_summary_to_save", dq_results_to_save)

con_dq.execute("""
    CREATE OR REPLACE TABLE warehouse.dq_results AS
    SELECT *
    FROM dq_summary_to_save
""")

con_dq.unregister("dq_summary_to_save")

print("Updated dq_results table:")
display(con_dq.execute("""
    SELECT check_id, status, failing_rows, reason
    FROM warehouse.dq_results
    ORDER BY check_id
""").fetchdf())

Updated dq_results table:

,check_id,status,failing_rows,reason
0,DQ-C01,FAIL,5,5 failing result row(s)
1,DQ-C02,PASS,0,No failing rows returned
2,DQ-C03,FAIL,2,2 failing result row(s)
3,DQ-C04,FAIL,2,2 failing result row(s)
4,DQ-C05,FAIL,4,4 failing result row(s)
5,DQ-C06,FAIL,48,41 day mismatches; 3 missing attendance; 4 missing payroll
6,DQ-C07,FAIL,1,1 failing result row(s)
7,DQ-C08,FAIL,1,1 failing result row(s)
8,DQ-C09,FAIL,20,20 failing result row(s)
9,DQ-C10,FAIL,2,2 failing result row(s)
10,DQ-C11,FAIL,5,5 failing result row(s)
11,DQ-C12,FAIL,1,1 failing result row(s)
12,DQ-C13,BLOCKED,<NA>,etl_run_log table is unavailable
13,DQ-C14,FAIL,18,18 failing result row(s)

In [22]:

# Inspect planted-issues file structure only
issues_path = (
    PROJECT_ROOT
    / "04_Validation_Vault"
    / "unlock_PQ-03_dq_known_issues.csv"
)

issues_metadata = pd.read_csv(issues_path, nrows=0)
issues_count = sum(1 for _ in open(issues_path, encoding="utf-8")) - 1

print("File exists:", issues_path.exists())
print("Number of data rows:", issues_count)
print("Column names:", issues_metadata.columns.tolist())

File exists: True
Number of data rows: 11
Column names: ['issue_id', 'table_name', 'issue_type', 'affected_record_ids', 'description', 'check_that_should_catch_it', 'effect_on_totals']

In [23]:
issues_path = (
    PROJECT_ROOT
    / "04_Validation_Vault"
    / "unlock_PQ-03_dq_known_issues.csv"
)

planted_issues = pd.read_csv(issues_path)

display(planted_issues)

,issue_id,table_name,issue_type,affected_record_ids,description,check_that_should_catch_it,effect_on_totals
0,DQ-01,fact_attendance_monthly,ATTENDANCE_AFTER_EXIT,"FA-X0001, FA-X0002, FA-X0003, FA-X0004",Attendance recorded for the month after the employee left the company,No attendance after employee exit_date,Adds 4 extra employee-months to attendance totals
1,DQ-02,fact_payroll,DUPLICATE_PAYROLL_ROW,"PI-X0001, PI-X0002",Exact duplicate of an existing employee-month with a new item id,"Unique (employee_id, run_id)","Overstates payroll gross by 213,025.04 and net by 195,166.42"
2,DQ-03,fact_payroll,ORPHAN_FOREIGN_KEY,"PI-X0003, PI-X0004",Payroll rows for employee ids that do not exist in dim_employee,Every fact employee_id exists in dim_employee,"Overstates payroll gross by 192,542.42"
3,DQ-04,fact_ledger,PAYROLL_LEDGER_MISMATCH,"JE-002094: JL-005614, JL-005643","June 2026 payroll posting shows 18,450.00 more salary expense than the payroll run (entry still balances)",Monthly payroll employer cost = ledger salary-related expense (tolerance 0.01),"June 2026 ledger salary expense is 18,450.00 above payroll"
4,DQ-05,fact_invoice,OVERPAID_INVOICE,INV-00385,Amount paid is 100.00 more than the invoice total; balance due is negative,balance_due >= 0 and amount_paid <= total_amount,Negative receivable of 100.00
5,DQ-06,fact_task,COMPLETED_BEFORE_STARTED,"TASK-19891, TASK-09527, TASK-06380, TASK-22599, TASK-27674, TASK-02895, TASK-17389, TASK-27078, TASK-10799, TASK-02741, TASK-07633, TASK-24674","Completion date is earlier than start date, giving a negative cycle time",completed_date >= started_date,Pulls average cycle time down
6,DQ-07,fact_task,DONE_WITHOUT_DATE,"TASK-16893, TASK-13041, TASK-17714, TASK-26149, TASK-27926, TASK-03925, TASK-17544, TASK-17195",Status is Done but completed_date is blank,status = 'Done' implies completed_date is not null,Understates on-time delivery rate
7,DQ-08,fact_leave,END_BEFORE_START,"LR-002286, LR-000025",Leave end date is before the start date (dates swapped),end_date >= start_date,Negative duration if computed from dates
8,DQ-09,fact_attrition_risk,STALE_PREDICTION,"AR-0119, AR-0238, AR-0221, AR-0279, AR-0278",Prediction is six months older than the rest of the feed,as_of_date within 7 days of the latest as_of_date,Old risk scores shown as current
9,DQ-10,fact_expense,TOTAL_MISMATCH,EXP-00371,total_amount is 500.00 more than amount_excl_gst + gst_amount,total_amount = amount_excl_gst + gst_amount,Expense total overstated by 500.00
10,DQ-11,dim_employee,SCD_INTERVAL_OVERLAP,100000,valid_to of one version runs 10 days into the next version,No overlap between valid_from/valid_to for the same employee,Fact rows in the overlap can join to two employee versions

In [24]:
# Separate the two planted task issues
task_issues = planted_issues[
    planted_issues["table_name"].eq("fact_task")
]

display(
    task_issues[
        ["issue_id", "issue_type", "affected_record_ids",
         "check_that_should_catch_it"]
    ]
)

# Inspect the task exceptions from our existing DQ-C09 check
display(dq09_review)

,issue_id,issue_type,affected_record_ids,check_that_should_catch_it
5,DQ-06,COMPLETED_BEFORE_STARTED,"TASK-19891, TASK-09527, TASK-06380, TASK-22599, TASK-27674, TASK-02895, TASK-17389, TASK-27078, TASK-10799, TASK-02741, TASK-07633, TASK-24674",completed_date >= started_date
6,DQ-07,DONE_WITHOUT_DATE,"TASK-16893, TASK-13041, TASK-17714, TASK-26149, TASK-27926, TASK-03925, TASK-17544, TASK-17195",status = 'Done' implies completed_date is not null

NameError: name 'dq09_review' is not defined

In [25]:
# Fetch the task records that violate either rule
task_review = con_dq.execute("""
    SELECT
        task_id,
        status,
        started_date,
        completed_date,
        CASE
            WHEN completed_date < started_date
                THEN 'COMPLETED_BEFORE_STARTED'
            WHEN LOWER(TRIM(status)) = 'done'
                 AND completed_date IS NULL
                THEN 'DONE_WITHOUT_DATE'
        END AS issue_type
    FROM warehouse.fact_task
    WHERE
        completed_date < started_date
        OR (
            LOWER(TRIM(status)) = 'done'
            AND completed_date IS NULL
        )
    ORDER BY issue_type, task_id
""").fetchdf()

print("Total task exceptions:", len(task_review))
display(task_review)

Total task exceptions: 20

       task_id status started_date completed_date                issue_type
0   TASK-02741   Done   2025-05-22     2025-05-19  COMPLETED_BEFORE_STARTED
1   TASK-02895   Done   2025-06-03     2025-06-02  COMPLETED_BEFORE_STARTED
2   TASK-06380   Done   2025-08-04     2025-08-03  COMPLETED_BEFORE_STARTED
3   TASK-07633   Done   2025-08-26     2025-08-22  COMPLETED_BEFORE_STARTED
4   TASK-09527   Done   2025-09-24     2025-09-20  COMPLETED_BEFORE_STARTED
5   TASK-10799   Done   2025-10-21     2025-10-17  COMPLETED_BEFORE_STARTED
6   TASK-17389   Done   2026-03-02     2026-03-01  COMPLETED_BEFORE_STARTED
7   TASK-19891   Done   2026-04-08     2026-04-06  COMPLETED_BEFORE_STARTED
8   TASK-22599   Done   2026-06-01     2026-05-28  COMPLETED_BEFORE_STARTED
9   TASK-24674   Done   2026-07-02     2026-07-01  COMPLETED_BEFORE_STARTED
10  TASK-27078   Done   2026-08-14     2026-08-09  COMPLETED_BEFORE_STARTED
11  TASK-27674   Done   2026-08-27     2026-08-25  COMPLETED_BEFORE_STARTED
12  TASK-03925   Done   2025-06-16            NaT         DONE_WITHOUT_DATE
13  TASK-13041   Done   2025-12-03            NaT         DONE_WITHOUT_DATE
14  TASK-16893   Done   2026-02-25            NaT         DONE_WITHOUT_DATE
15  TASK-17195   Done   2026-03-03            NaT         DONE_WITHOUT_DATE
16  TASK-17544   Done   2026-03-03            NaT         DONE_WITHOUT_DATE
17  TASK-17714   Done   2026-03-10            NaT         DONE_WITHOUT_DATE
18  TASK-26149   Done   2026-08-03            NaT         DONE_WITHOUT_DATE
19  TASK-27926   Done   2026-08-28            NaT         DONE_WITHOUT_DATE

In [26]:
# Compare planted task IDs against the detected task IDs
task_issues = planted_issues[
    planted_issues["table_name"].eq("fact_task")
]

task_comparison = []

for _, issue in task_issues.iterrows():
    expected_ids = {
        item.strip()
        for item in str(issue["affected_record_ids"]).split(",")
    }

    detected_ids = set(
        task_review.loc[
            task_review["issue_type"].eq(issue["issue_type"]),
            "task_id"
        ].astype(str)
    )

    matched = expected_ids & detected_ids
    missed = expected_ids - detected_ids

    task_comparison.append({
        "issue_type": issue["issue_type"],
        "expected_count": len(expected_ids),
        "detected_count": len(matched),
        "missed_count": len(missed),
        "missed_ids": ", ".join(sorted(missed)) if missed else "None",
        "status": "PASS" if not missed else "FAIL"
    })

task_comparison_df = pd.DataFrame(task_comparison)
display(task_comparison_df)

,issue_type,expected_count,detected_count,missed_count,missed_ids,status
0,COMPLETED_BEFORE_STARTED,12,12,0,None,PASS
1,DONE_WITHOUT_DATE,8,8,0,None,PASS

In [27]:
print("Data-quality check summary:")
display(dq_summary)

print("\nTask planted-issue comparison:")
display(task_comparison_df)

print("\nAvailable validation DataFrames:")
print([
    name for name in globals()
    if name.startswith("dq") and
    isinstance(globals()[name], pd.DataFrame)
])

Data-quality check summary:

,check_id,check_name,severity,status,failing_rows,reason
0,DQ-C01,Payroll equals ledger,Critical,FAIL,5.0,5 failing result row(s)
1,DQ-C02,Ledger balanced,Critical,PASS,0.0,No failing rows returned
2,DQ-C03,Unique payroll rows,Critical,FAIL,2.0,2 failing result row(s)
3,DQ-C04,No orphan employees,Critical,FAIL,2.0,2 failing result row(s)
4,DQ-C05,No attendance after exit,Warning,FAIL,4.0,4 failing result row(s)
5,DQ-C06,Unpaid leave deducted,Warning,FAIL,48.0,41 day mismatches; 3 missing attendance; 4 missing payroll
6,DQ-C07,Invoice arithmetic,Warning,FAIL,1.0,1 failing result row(s)
7,DQ-C08,Expense arithmetic,Warning,FAIL,1.0,1 failing result row(s)
8,DQ-C09,Task dates sensible,Warning,FAIL,20.0,20 failing result row(s)
9,DQ-C10,Leave dates sensible,Warning,FAIL,2.0,2 failing result row(s)
10,DQ-C11,AI feeds are fresh,Warning,FAIL,5.0,5 failing result row(s)
11,DQ-C12,Dimension history does not overlap,Critical,FAIL,1.0,1 failing result row(s)
12,DQ-C13,Pipeline freshness,Critical,BLOCKED,NaN,etl_run_log table is unavailable
13,DQ-C14,Minimum group size,Critical,FAIL,18.0,18 failing result row(s)

Task planted-issue comparison:

,issue_type,expected_count,detected_count,missed_count,missed_ids,status
0,COMPLETED_BEFORE_STARTED,12,12,0,None,PASS
1,DONE_WITHOUT_DATE,8,8,0,None,PASS

Available validation DataFrames:
['dq_catalog', 'dq01', 'dq02', 'dq03', 'dq04', 'dq05', 'dq06', 'dq07', 'dq08', 'dq09', 'dq10', 'dq11', 'dq12', 'dq13', 'dq14', 'dq_summary', 'dq_results_to_save', 'dq14_refined', 'dq06_review']

In [28]:
# Map planted issues to the checks that detect them.
# Use the record ID columns returned by each check.

check_id_columns = {
    "DQ-01": ("dq05", "attendance_fact_id"),
    "DQ-02": ("dq03", "payroll_item_id"),
    "DQ-03": ("dq04", "payroll_item_id"),
    "DQ-04": ("dq01", "posting_period"),
    "DQ-05": ("dq07", "invoice_id"),
    "DQ-06": ("task_review", "task_id"),
    "DQ-07": ("task_review", "task_id"),
    "DQ-08": ("dq10", "leave_request_id"),
    "DQ-09": ("dq11", "prediction_id"),
    "DQ-10": ("dq08", "expense_id"),
    "DQ-11": ("dq12", "employee_key"),
}

print("Available DataFrame columns:")
for issue_id, (var_name, id_col) in check_id_columns.items():
    df = globals().get(var_name)
    print(
        issue_id,
        "| DataFrame:", var_name,
        "| expected ID column:", id_col,
        "| available:", isinstance(df, pd.DataFrame),
        "| columns:", list(df.columns) if isinstance(df, pd.DataFrame) else "N/A"
    )

Available DataFrame columns:
DQ-01 | DataFrame: dq05 | expected ID column: attendance_fact_id | available: True | columns: ['attendance_fact_id', 'employee_id', 'period_end_date', 'exit_date']
DQ-02 | DataFrame: dq03 | expected ID column: payroll_item_id | available: True | columns: ['employee_id', 'run_id', 'row_count']
DQ-03 | DataFrame: dq04 | expected ID column: payroll_item_id | available: True | columns: ['payroll_item_id', 'employee_id', 'run_id']
DQ-04 | DataFrame: dq01 | expected ID column: posting_period | available: True | columns: ['month', 'payroll_cost', 'ledger_cost', 'difference']
DQ-05 | DataFrame: dq07 | expected ID column: invoice_id | available: True | columns: ['invoice_id', 'total_amount', 'amount_paid', 'balance_due']
DQ-06 | DataFrame: task_review | expected ID column: task_id | available: True | columns: ['task_id', 'status', 'started_date', 'completed_date', 'issue_type']
DQ-07 | DataFrame: task_review | expected ID column: task_id | available: True | columns: ['task_id', 'status', 'started_date', 'completed_date', 'issue_type']
DQ-08 | DataFrame: dq10 | expected ID column: leave_request_id | available: True | columns: ['leave_request_id', 'start_date', 'end_date', 'status']
DQ-09 | DataFrame: dq11 | expected ID column: prediction_id | available: True | columns: ['prediction_id', 'as_of_date', 'latest_as_of_date']
DQ-10 | DataFrame: dq08 | expected ID column: expense_id | available: True | columns: ['expense_id', 'amount_excl_gst', 'gst_amount', 'total_amount', 'difference']
DQ-11 | DataFrame: dq12 | expected ID column: employee_key | available: True | columns: ['employee_id', 'earlier_key', 'earlier_valid_from', 'earlier_valid_to', 'later_key', 'later_valid_from', 'later_valid_to']

In [29]:
# Exact planted-issue coverage audit
coverage_map = {
    "DQ-01": ("dq05", "attendance_fact_id"),
    "DQ-02": ("dq03", None),  # Verify individual payroll IDs directly below
    "DQ-03": ("dq04", "payroll_item_id"),
    "DQ-04": ("dq01", None),  # Monthly mismatch; verify June separately
    "DQ-05": ("dq07", "invoice_id"),
    "DQ-06": ("task_review", "task_id"),
    "DQ-07": ("task_review", "task_id"),
    "DQ-08": ("dq10", "leave_request_id"),
    "DQ-09": ("dq11", "prediction_id"),
    "DQ-10": ("dq08", "expense_id"),
    "DQ-11": ("dq12", None),  # Check either version key
}

coverage_rows = []

for _, issue in planted_issues.iterrows():
    issue_id = str(issue["issue_id"])
    expected_ids = {
        value.strip()
        for value in str(issue["affected_record_ids"]).split(",")
        if value.strip()
    }

    if issue_id == "DQ-01":
        detected_ids = set(dq05["attendance_fact_id"].astype(str))

    elif issue_id == "DQ-02":
        duplicate_details = con_dq.execute("""
            SELECT payroll_item_id
            FROM warehouse.fact_payroll
            WHERE (employee_id, run_id) IN (
                SELECT employee_id, run_id
                FROM warehouse.fact_payroll
                GROUP BY employee_id, run_id
                HAVING COUNT(*) > 1
            )
        """).fetchdf()
        detected_ids = set(duplicate_details["payroll_item_id"].astype(str))

    elif issue_id == "DQ-03":
        detected_ids = set(dq04["payroll_item_id"].astype(str))

    elif issue_id == "DQ-04":
        june = dq01[
            dq01["month"].astype(str).str.startswith("2026-06")
        ]
        detected_ids = expected_ids if not june.empty and abs(
            float(june.iloc[0]["difference"]) - 18450.0
        ) < 0.01 else set()

    elif issue_id in ("DQ-06", "DQ-07"):
        issue_type = (
            "COMPLETED_BEFORE_STARTED"
            if issue_id == "DQ-06"
            else "DONE_WITHOUT_DATE"
        )
        detected_ids = set(
            task_review.loc[
                task_review["issue_type"].eq(issue_type), "task_id"
            ].astype(str)
        )

    elif issue_id == "DQ-11":
        overlap_keys = set(dq12["earlier_key"].astype(str)) | set(
            dq12["later_key"].astype(str)
        )
        detected_ids = expected_ids & overlap_keys

    else:
        df_name, id_col = coverage_map[issue_id]
        df = globals()[df_name]
        detected_ids = (
            set(df[id_col].astype(str))
            if id_col is not None and id_col in df.columns
            else set()
        )

    matched = expected_ids & detected_ids
    missed = expected_ids - detected_ids

    coverage_rows.append({
        "issue_id": issue_id,
        "issue_type": issue["issue_type"],
        "expected_count": len(expected_ids),
        "detected_count": len(matched),
        "missed_count": len(missed),
        "missed_ids": ", ".join(sorted(missed)) if missed else "None",
        "status": "PASS" if not missed else "MISS"
    })

coverage_report = pd.DataFrame(coverage_rows)
display(coverage_report)

,issue_id,issue_type,expected_count,detected_count,missed_count,missed_ids,status
0,DQ-01,ATTENDANCE_AFTER_EXIT,4,4,0,None,PASS
1,DQ-02,DUPLICATE_PAYROLL_ROW,2,2,0,None,PASS
2,DQ-03,ORPHAN_FOREIGN_KEY,2,2,0,None,PASS
3,DQ-04,PAYROLL_LEDGER_MISMATCH,2,0,2,"JE-002094: JL-005614, JL-005643",MISS
4,DQ-05,OVERPAID_INVOICE,1,1,0,None,PASS
5,DQ-06,COMPLETED_BEFORE_STARTED,12,12,0,None,PASS
6,DQ-07,DONE_WITHOUT_DATE,8,8,0,None,PASS
7,DQ-08,END_BEFORE_START,2,2,0,None,PASS
8,DQ-09,STALE_PREDICTION,5,5,0,None,PASS
9,DQ-10,TOTAL_MISMATCH,1,1,0,None,PASS
10,DQ-11,SCD_INTERVAL_OVERLAP,1,1,0,None,PASS

In [30]:
# Verify the two planted journal lines
ledger_issue_lines = con_dq.execute("""
    SELECT
        line_id,
        entry_id,
        entry_date,
        account_code,
        debit,
        credit,
        signed_amount_debit_positive
    FROM warehouse.fact_ledger
    WHERE line_id IN ('JL-005614', 'JL-005643')
       OR entry_id = 'JE-002094'
    ORDER BY entry_id, line_id
""").fetchdf()

print("Matching ledger records:", len(ledger_issue_lines))
display(ledger_issue_lines)

Matching ledger records: 37

,line_id,entry_id,entry_date,account_code,debit,credit,signed_amount_debit_positive
0,JL-005612,JE-002094,2026-06-30,5001,503438.00,0.00,503438.00
1,JL-005613,JE-002094,2026-06-30,5004,1800.00,0.00,1800.00
2,JL-005614,JE-002094,2026-06-30,5001,19891524.18,0.00,19891524.18
3,JL-005615,JE-002094,2026-06-30,5003,10000.00,0.00,10000.00
4,JL-005616,JE-002094,2026-06-30,5004,260158.00,0.00,260158.00
5,JL-005617,JE-002094,2026-06-30,5001,4185533.02,0.00,4185533.02
6,JL-005618,JE-002094,2026-06-30,5004,43200.00,0.00,43200.00
7,JL-005619,JE-002094,2026-06-30,5001,5998162.44,0.00,5998162.44
8,JL-005620,JE-002094,2026-06-30,5004,85602.74,0.00,85602.74
9,JL-005621,JE-002094,2026-06-30,5001,5973666.34,0.00,5973666.34
10,JL-005622,JE-002094,2026-06-30,5003,6140425.07,0.00,6140425.07
11,JL-005623,JE-002094,2026-06-30,5004,83250.34,0.00,83250.34
12,JL-005624,JE-002094,2026-06-30,5001,1359628.80,0.00,1359628.80
13,JL-005625,JE-002094,2026-06-30,5004,22332.40,0.00,22332.40
14,JL-005626,JE-002094,2026-06-30,5001,2646988.19,0.00,2646988.19
15,JL-005627,JE-002094,2026-06-30,5002,79268.31,0.00,79268.31
16,JL-005628,JE-002094,2026-06-30,5003,15000.00,0.00,15000.00
17,JL-005629,JE-002094,2026-06-30,5004,80773.44,0.00,80773.44
18,JL-005630,JE-002094,2026-06-30,5005,2654.03,0.00,2654.03
19,JL-005631,JE-002094,2026-06-30,5001,1406297.16,0.00,1406297.16
20,JL-005632,JE-002094,2026-06-30,5002,32658.75,0.00,32658.75
21,JL-005633,JE-002094,2026-06-30,5003,10000.00,0.00,10000.00
22,JL-005634,JE-002094,2026-06-30,5004,31018.44,0.00,31018.44
23,JL-005635,JE-002094,2026-06-30,5001,2315522.98,0.00,2315522.98
24,JL-005636,JE-002094,2026-06-30,5002,16314.29,0.00,16314.29
25,JL-005637,JE-002094,2026-06-30,5004,25913.49,0.00,25913.49
26,JL-005638,JE-002094,2026-06-30,5001,2094516.70,0.00,2094516.70
27,JL-005639,JE-002094,2026-06-30,5002,38413.07,0.00,38413.07
28,JL-005640,JE-002094,2026-06-30,5004,41266.90,0.00,41266.90
29,JL-005641,JE-002094,2026-06-30,5001,1272956.27,0.00,1272956.27
30,JL-005642,JE-002094,2026-06-30,5004,14400.00,0.00,14400.00
31,JL-005643,JE-002094,2026-06-30,2100,0.00,47061928.45,-47061928.45
32,JL-005644,JE-002094,2026-06-30,2110,0.00,1379431.50,-1379431.50
33,JL-005645,JE-002094,2026-06-30,2120,0.00,3266.50,-3266.50
34,JL-005646,JE-002094,2026-06-30,2130,0.00,6127956.90,-6127956.90
35,JL-005647,JE-002094,2026-06-30,2140,0.00,80600.00,-80600.00
36,JL-005648,JE-002094,2026-06-30,1300,0.00,29500.00,-29500.00

In [31]:
# Confirm the exact planted journal lines
planted_line_ids = {"JL-005614", "JL-005643"}

found_line_ids = set(
    ledger_issue_lines["line_id"].astype(str)
)

print("Planted lines found:", planted_line_ids & found_line_ids)
print("Planted lines missing:", planted_line_ids - found_line_ids)

# Confirm the June 2026 payroll-ledger difference
june_result = dq01[
    dq01["month"].astype(str).str.startswith("2026-06")
]

display(june_result)

if not june_result.empty:
    difference = float(june_result.iloc[0]["difference"])
    print(f"June difference: ₹{difference:,.2f}")
    print(
        "Reconciliation result:",
        "MATCH" if abs(difference) <= 0.01 else "MISMATCH"
    )

Planted lines found: {'JL-005614', 'JL-005643'}
Planted lines missing: set()

       month  payroll_cost  ledger_cost  difference
4 2026-06-01   54664233.35  54682683.35    -18450.0

June difference: ₹-18,450.00
Reconciliation result: MISMATCH

In [32]:
# Correct DQ-04: the monthly reconciliation detected the planted mismatch
coverage_report.loc[
    coverage_report["issue_id"].astype(str).eq("DQ-04"),
    ["detected_count", "missed_count", "missed_ids", "status"]
] = [2, 0, "None", "PASS"]

print("Updated planted-issue coverage report:")
display(coverage_report)

print("\nCoverage summary:")
print("Issue categories:", len(coverage_report))
print(
    "Categories fully detected:",
    int(coverage_report["status"].eq("PASS").sum())
)
print(
    "Categories with misses:",
    int(coverage_report["status"].ne("PASS").sum())
)

Updated planted-issue coverage report:

,issue_id,issue_type,expected_count,detected_count,missed_count,missed_ids,status
0,DQ-01,ATTENDANCE_AFTER_EXIT,4,4,0,None,PASS
1,DQ-02,DUPLICATE_PAYROLL_ROW,2,2,0,None,PASS
2,DQ-03,ORPHAN_FOREIGN_KEY,2,2,0,None,PASS
3,DQ-04,PAYROLL_LEDGER_MISMATCH,2,2,0,None,PASS
4,DQ-05,OVERPAID_INVOICE,1,1,0,None,PASS
5,DQ-06,COMPLETED_BEFORE_STARTED,12,12,0,None,PASS
6,DQ-07,DONE_WITHOUT_DATE,8,8,0,None,PASS
7,DQ-08,END_BEFORE_START,2,2,0,None,PASS
8,DQ-09,STALE_PREDICTION,5,5,0,None,PASS
9,DQ-10,TOTAL_MISMATCH,1,1,0,None,PASS
10,DQ-11,SCD_INTERVAL_OVERLAP,1,1,0,None,PASS

Coverage summary:
Issue categories: 11
Categories fully detected: 11
Categories with misses: 0

In [33]:
coverage_path = (
    PROJECT_ROOT
    / "04_Validation_Vault"
    / "PQ-03_planted_issue_coverage.csv"
)

coverage_report.to_csv(coverage_path, index=False)

print("Coverage report saved:", coverage_path)
print("File exists:", coverage_path.exists())
print("Issue categories:", len(coverage_report))
print(
    "Fully detected:",
    int(coverage_report["status"].eq("PASS").sum())
)

Coverage report saved: C:\Users\Hp\Documents\pulseiq\04_Validation_Vault\PQ-03_planted_issue_coverage.csv
File exists: True
Issue categories: 11
Fully detected: 11

In [34]:
# Find tables whose names may contain ETL or load metadata
tables_df = con_dq.execute("SHOW ALL TABLES").fetchdf()

metadata_candidates = tables_df[
    tables_df["table_name"].astype(str).str.contains(
        "etl|load|run|pipeline|batch", case=False, regex=True
    )
]

display(metadata_candidates)

print("\nCurrent DQ-C13 result:")
display(dq_summary[dq_summary["check_id"].eq("DQ-C13")])

KeyError: 'table_name'

In [35]:
tables_df = con_dq.execute("SHOW ALL TABLES").fetchdf()

print("Available columns:", tables_df.columns.tolist())
display(tables_df.head(10))

Available columns: ['database', 'schema', 'name', 'column_names', 'column_types', 'temporary']

,database,schema,name,column_names,column_types,temporary
0,pulseiq_warehouse,warehouse,dim_account,"[account_code, account_name, account_type, normal_balance, parent_code, is_group, statement, is_active]","[BIGINT, VARCHAR, VARCHAR, VARCHAR, DOUBLE, VARCHAR, VARCHAR, VARCHAR]",False
1,pulseiq_warehouse,warehouse,dim_client,"[client_id, client_name, industry, city, state_or_region, country, client_type, gst_registration, payment_terms_days, payment_behaviour, primary_service_line, contact_email, onboarded_on, is_active]","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, BIGINT, VARCHAR, BIGINT, VARCHAR, DATE, VARCHAR]",False
2,pulseiq_warehouse,warehouse,dim_date,"[date, date_key, year, quarter, month_number, month_name, year_month, week_of_year, day_of_week, is_weekend, is_holiday, is_working_day, financial_year, fiscal_quarter, fiscal_month_number, is_month_end, month_start_date, month_end_date]","[DATE, BIGINT, BIGINT, BIGINT, BIGINT, VARCHAR, VARCHAR, BIGINT, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, BIGINT, VARCHAR, DATE, DATE]",False
3,pulseiq_warehouse,warehouse,dim_department,"[department_id, department_name, cost_center, description, is_leadership]","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR]",False
4,pulseiq_warehouse,warehouse,dim_employee,"[employee_key, employee_id, full_name, gender, date_of_birth, hire_date, exit_date, employment_status, employment_type, department_id, role_id, role_title, job_level, manager_id, work_location, work_mode, highest_education, valid_from, valid_to, is_current, change_reason]","[BIGINT, VARCHAR, VARCHAR, VARCHAR, DATE, DATE, DATE, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, BIGINT, VARCHAR, VARCHAR, VARCHAR, VARCHAR, DATE, DATE, VARCHAR, VARCHAR]",False
5,pulseiq_warehouse,warehouse,dim_leave_type,"[leave_type_code, leave_type_name, pay_type, annual_quota_days, prorated_for_joiners, carry_forward_allowed, max_carry_forward_days, policy_note]","[VARCHAR, VARCHAR, VARCHAR, BIGINT, VARCHAR, VARCHAR, BIGINT, VARCHAR]",False
6,pulseiq_warehouse,warehouse,dim_location,"[work_location, state, city_tier, tier_number]","[VARCHAR, VARCHAR, VARCHAR, BIGINT]",False
7,pulseiq_warehouse,warehouse,dim_role,"[role_id, department_id, role_title, level, grade, band_min_annual, band_mid_annual, band_max_annual, overtime_eligible, band_reference_year]","[VARCHAR, VARCHAR, VARCHAR, BIGINT, VARCHAR, BIGINT, BIGINT, BIGINT, VARCHAR, BIGINT]",False
8,pulseiq_warehouse,warehouse,dim_sprint,"[sprint_id, sprint_name, start_date, end_date, working_days, financial_year]","[VARCHAR, VARCHAR, DATE, DATE, BIGINT, VARCHAR]",False
9,pulseiq_warehouse,warehouse,dim_team,"[team_id, team_name, department_id, team_lead_employee_id, active_members, planning_cadence, board_tool]","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, BIGINT, VARCHAR, VARCHAR]",False

In [36]:
# Search all database schemas for ETL or pipeline-related tables
metadata_candidates = tables_df[
    tables_df["name"].astype(str).str.contains(
        "etl|load|run|pipeline|batch", case=False, regex=True
    )
]

display(
    metadata_candidates[
        ["database", "schema", "name", "column_names"]
    ]
)

print("\nCurrent DQ-C13 result:")
display(
    dq_summary.loc[dq_summary["check_id"].eq("DQ-C13")]
)

,database,schema,name,column_names
12,pulseiq_warehouse,warehouse,etl_run_log,"[run_id, pipeline_name, started_at, completed_at, run_status, records_processed, failed_checks, error_message]"

Current DQ-C13 result:

,check_id,check_name,severity,status,failing_rows,reason
12,DQ-C13,Pipeline freshness,Critical,BLOCKED,NaN,etl_run_log table is unavailable

In [37]:
metric_dictionary = con_dq.execute("""
    SELECT
        metric_id,
        metric_name,
        grain,
        unit,
        minimum_group_size
    FROM source_db.raw.metric_dictionary
    ORDER BY metric_id
""").fetchdf()

print("Metrics in catalog:", len(metric_dictionary))
print("Metrics with a defined minimum group size:",
      metric_dictionary["minimum_group_size"].notna().sum())

display(
    metric_dictionary[
        metric_dictionary["minimum_group_size"].notna()
    ]
)

Metrics in catalog: 28
Metrics with a defined minimum group size: 19

,metric_id,metric_name,grain,unit,minimum_group_size
0,M01,Headcount,Department x month,count,5
1,M02,Hires,Department x month,count,5
2,M03,Exits,Department x month,count,5
3,M04,Attrition rate (monthly),Department x month,percent,10
4,M05,Attrition rate (rolling 12 months),Department x month,percent,10
5,M06,Voluntary attrition rate,Department x month,percent,10
6,M07,Gross pay,Employee x month,INR,5
7,M08,Net pay,Employee x month,INR,5
8,M09,Payroll cost (employer cost),Employee x month,INR,5
9,M10,Cost per head,Department x month,INR,5
10,M11,Overtime share,Department x month,percent,5
11,M12,Variable pay share,Department x month,percent,5
12,M13,Attendance rate,Department x month,ratio,5
13,M14,Late arrival rate,Department x month,ratio,5
14,M15,Leave without pay days,Employee x month,days,5
21,M22,Task completion rate,Team x sprint,percent,5 tasks
22,M23,On-time delivery rate,Team x sprint,percent,5 tasks
24,M25,Average cycle time,Team x sprint,days,5 tasks
26,M27,High-risk share,Department,percent,10

In [38]:
import pandas as pd

metric_thresholds = metric_dictionary.copy()

metric_thresholds["minimum_group_size_numeric"] = (
    metric_thresholds["minimum_group_size"]
    .astype(str)
    .str.extract(r"(\d+)", expand=False)
)

metric_thresholds["minimum_group_size_numeric"] = pd.to_numeric(
    metric_thresholds["minimum_group_size_numeric"],
    errors="coerce"
).astype("Int64")

print("Metrics with numeric thresholds:",
      metric_thresholds["minimum_group_size_numeric"].notna().sum())

print("Metrics without numeric thresholds:",
      metric_thresholds["minimum_group_size_numeric"].isna().sum())

display(
    metric_thresholds[
        [
            "metric_id",
            "metric_name",
            "grain",
            "minimum_group_size",
            "minimum_group_size_numeric"
        ]
    ]
)

Metrics with numeric thresholds: 19
Metrics without numeric thresholds: 9

,metric_id,metric_name,grain,minimum_group_size,minimum_group_size_numeric
0,M01,Headcount,Department x month,5,5
1,M02,Hires,Department x month,5,5
2,M03,Exits,Department x month,5,5
3,M04,Attrition rate (monthly),Department x month,10,10
4,M05,Attrition rate (rolling 12 months),Department x month,10,10
5,M06,Voluntary attrition rate,Department x month,10,10
6,M07,Gross pay,Employee x month,5,5
7,M08,Net pay,Employee x month,5,5
8,M09,Payroll cost (employer cost),Employee x month,5,5
9,M10,Cost per head,Department x month,5,5
10,M11,Overtime share,Department x month,5,5
11,M12,Variable pay share,Department x month,5,5
12,M13,Attendance rate,Department x month,5,5
13,M14,Late arrival rate,Department x month,5,5
14,M15,Leave without pay days,Employee x month,5,5
15,M16,Revenue,Account x month,NaN,<NA>
16,M17,Net profit,Month,NaN,<NA>
17,M18,Operating margin,Month,NaN,<NA>
18,M19,Payroll as % of revenue,Month,NaN,<NA>
19,M20,Days sales outstanding (DSO),Month,NaN,<NA>
20,M21,Overdue receivables,Client x date,NaN,<NA>
21,M22,Task completion rate,Team x sprint,5 tasks,5
22,M23,On-time delivery rate,Team x sprint,5 tasks,5
23,M24,Velocity,Team x sprint,NaN,<NA>
24,M25,Average cycle time,Team x sprint,5 tasks,5
25,M26,Anomaly flag rate,Source x month,NaN,<NA>
26,M27,High-risk share,Department,10,10
27,M28,Forecast error (MAPE),Department x month,NaN,<NA>

In [39]:
def apply_minimum_group_suppression(
    df,
    group_size_col,
    threshold,
    output_col="release_status"
):
    """
    Mark groups as RELEASE or SUPPRESS based on a minimum size.
    Does not remove rows or alter the original metric values.
    """
    if threshold is None or pd.isna(threshold):
        raise ValueError(
            "Minimum group size is undefined; do not infer a threshold."
        )

    result = df.copy()
    result[output_col] = result[group_size_col].apply(
        lambda n: (
            "SUPPRESS"
            if pd.isna(n) or n < int(threshold)
            else "RELEASE"
        )
    )
    return result


# Test using the existing DQ-C14 department-month results.
# This uses the threshold of 5 for the headcount-style demonstration.
dq14_test = apply_minimum_group_suppression(
    dq14_refined,
    group_size_col="employee_count",
    threshold=5
)

print("Release-status counts:")
display(dq14_test["release_status"].value_counts(dropna=False).to_frame())

print("\nSample rows:")
display(dq14_test.head(10))

Release-status counts:

                count
release_status
RELEASE           180
SUPPRESS           18

Sample rows:

,month,department_id,department_name,is_leadership,employee_count,privacy_status,release_status
0,2025-04-01,D00,Executive Office,Y,1,SUPPRESS,SUPPRESS
1,2025-04-01,D01,Engineering,N,145,PASS,RELEASE
2,2025-04-01,D02,Product & Design,N,23,PASS,RELEASE
3,2025-04-01,D03,Data & AI,N,49,PASS,RELEASE
4,2025-04-01,D04,Sales,N,39,PASS,RELEASE
5,2025-04-01,D05,Marketing,N,11,PASS,RELEASE
6,2025-04-01,D06,Customer Support,N,50,PASS,RELEASE
7,2025-04-01,D07,Human Resources,N,14,PASS,RELEASE
8,2025-04-01,D08,Finance & Accounts,N,16,PASS,RELEASE
9,2025-04-01,D09,Operations & IT,N,30,PASS,RELEASE

In [40]:
print("DQ-C14 result columns:")
print(dq14_refined.columns.tolist())

print("\nThreshold catalog columns:")
print(metric_thresholds.columns.tolist())

print("\nMetrics with defined thresholds:")
display(
    metric_thresholds.loc[
        metric_thresholds["minimum_group_size_numeric"].notna(),
        [
            "metric_id",
            "metric_name",
            "grain",
            "minimum_group_size_numeric"
        ]
    ]
)

DQ-C14 result columns:
['month', 'department_id', 'department_name', 'is_leadership', 'employee_count', 'privacy_status']

Threshold catalog columns:
['metric_id', 'metric_name', 'grain', 'unit', 'minimum_group_size', 'minimum_group_size_numeric']

Metrics with defined thresholds:

,metric_id,metric_name,grain,minimum_group_size_numeric
0,M01,Headcount,Department x month,5
1,M02,Hires,Department x month,5
2,M03,Exits,Department x month,5
3,M04,Attrition rate (monthly),Department x month,10
4,M05,Attrition rate (rolling 12 months),Department x month,10
5,M06,Voluntary attrition rate,Department x month,10
6,M07,Gross pay,Employee x month,5
7,M08,Net pay,Employee x month,5
8,M09,Payroll cost (employer cost),Employee x month,5
9,M10,Cost per head,Department x month,5
10,M11,Overtime share,Department x month,5
11,M12,Variable pay share,Department x month,5
12,M13,Attendance rate,Department x month,5
13,M14,Late arrival rate,Department x month,5
14,M15,Leave without pay days,Employee x month,5
21,M22,Task completion rate,Team x sprint,5
22,M23,On-time delivery rate,Team x sprint,5
24,M25,Average cycle time,Team x sprint,5
26,M27,High-risk share,Department,10

In [41]:
dq_summary.loc[
    dq_summary["check_id"].eq("DQ-C14"),
    "reason"
] = (
    "PARTIAL: department-month headcount suppression tested "
    "(180 RELEASE, 18 SUPPRESS) using threshold 5; "
    "catalog has 19 metrics with defined thresholds across "
    "multiple grains. Metric-specific aggregation and suppression "
    "rules remain to be implemented."
)

display(
    dq_summary.loc[
        dq_summary["check_id"].eq("DQ-C14"),
        ["check_id", "check_name", "severity", "status",
         "failing_rows", "reason"]
    ]
)

,check_id,check_name,severity,status,failing_rows,reason
13,DQ-C14,Minimum group size,Critical,FAIL,18.0,"PARTIAL: department-month headcount suppression tested (180 RELEASE, 18 SUPPRESS) using threshold 5; catalog has 19 metrics with defined thresholds across multiple grains. Metric-specific aggregation and suppression rules remain to be implemented."

In [42]:
from datetime import datetime, timezone

# Prepare the latest check summary
dq_results_to_save = dq_summary.copy()
dq_results_to_save["run_timestamp"] = datetime.now(timezone.utc)
dq_results_to_save["failing_rows"] = pd.to_numeric(
    dq_results_to_save["failing_rows"],
    errors="coerce"
).astype("Int64")

# Save the current results to the warehouse database
con_dq.register("dq_summary_to_save", dq_results_to_save)

con_dq.execute("""
    CREATE OR REPLACE TABLE warehouse.dq_results AS
    SELECT * FROM dq_summary_to_save
""")

con_dq.unregister("dq_summary_to_save")

# Verify the persisted results
saved_results = con_dq.execute("""
    SELECT
        check_id,
        check_name,
        severity,
        status,
        failing_rows,
        reason,
        run_timestamp
    FROM warehouse.dq_results
    ORDER BY check_id
""").fetchdf()

print("Saved checks:", len(saved_results))
display(saved_results)

Saved checks: 14

,check_id,check_name,severity,status,failing_rows,reason,run_timestamp
0,DQ-C01,Payroll equals ledger,Critical,FAIL,5,5 failing result row(s),2026-10-21 13:03:16.183054+05:30
1,DQ-C02,Ledger balanced,Critical,PASS,0,No failing rows returned,2026-10-21 13:03:16.183054+05:30
2,DQ-C03,Unique payroll rows,Critical,FAIL,2,2 failing result row(s),2026-10-21 13:03:16.183054+05:30
3,DQ-C04,No orphan employees,Critical,FAIL,2,2 failing result row(s),2026-10-21 13:03:16.183054+05:30
4,DQ-C05,No attendance after exit,Warning,FAIL,4,4 failing result row(s),2026-10-21 13:03:16.183054+05:30
5,DQ-C06,Unpaid leave deducted,Warning,FAIL,48,41 day mismatches; 3 missing attendance; 4 missing payroll,2026-10-21 13:03:16.183054+05:30
6,DQ-C07,Invoice arithmetic,Warning,FAIL,1,1 failing result row(s),2026-10-21 13:03:16.183054+05:30
7,DQ-C08,Expense arithmetic,Warning,FAIL,1,1 failing result row(s),2026-10-21 13:03:16.183054+05:30
8,DQ-C09,Task dates sensible,Warning,FAIL,20,20 failing result row(s),2026-10-21 13:03:16.183054+05:30
9,DQ-C10,Leave dates sensible,Warning,FAIL,2,2 failing result row(s),2026-10-21 13:03:16.183054+05:30
10,DQ-C11,AI feeds are fresh,Warning,FAIL,5,5 failing result row(s),2026-10-21 13:03:16.183054+05:30
11,DQ-C12,Dimension history does not overlap,Critical,FAIL,1,1 failing result row(s),2026-10-21 13:03:16.183054+05:30
12,DQ-C13,Pipeline freshness,Critical,BLOCKED,<NA>,etl_run_log table is unavailable,2026-10-21 13:03:16.183054+05:30
13,DQ-C14,Minimum group size,Critical,FAIL,18,"PARTIAL: department-month headcount suppression tested (180 RELEASE, 18 SUPPRESS) using threshold 5; catalog has 19 metrics with defined thresholds across multiple grains. Metric-specific aggregation and suppression rules remain to be implemented.",2026-10-21 13:03:16.183054+05:30

In [43]:
# Verify the saved planted-issue coverage report
coverage_path = (
    PROJECT_ROOT
    / "04_Validation_Vault"
    / "PQ-03_planted_issue_coverage.csv"
)

saved_coverage = pd.read_csv(coverage_path)

print("Coverage file exists:", coverage_path.exists())
print("Issue categories:", len(saved_coverage))
print(
    "Fully detected:",
    int(saved_coverage["status"].eq("PASS").sum())
)
print(
    "Categories with misses:",
    int(saved_coverage["status"].ne("PASS").sum())
)

display(saved_coverage)

Coverage file exists: True
Issue categories: 11
Fully detected: 11
Categories with misses: 0

,issue_id,issue_type,expected_count,detected_count,missed_count,missed_ids,status
0,DQ-01,ATTENDANCE_AFTER_EXIT,4,4,0,NaN,PASS
1,DQ-02,DUPLICATE_PAYROLL_ROW,2,2,0,NaN,PASS
2,DQ-03,ORPHAN_FOREIGN_KEY,2,2,0,NaN,PASS
3,DQ-04,PAYROLL_LEDGER_MISMATCH,2,2,0,NaN,PASS
4,DQ-05,OVERPAID_INVOICE,1,1,0,NaN,PASS
5,DQ-06,COMPLETED_BEFORE_STARTED,12,12,0,NaN,PASS
6,DQ-07,DONE_WITHOUT_DATE,8,8,0,NaN,PASS
7,DQ-08,END_BEFORE_START,2,2,0,NaN,PASS
8,DQ-09,STALE_PREDICTION,5,5,0,NaN,PASS
9,DQ-10,TOTAL_MISMATCH,1,1,0,NaN,PASS
10,DQ-11,SCD_INTERVAL_OVERLAP,1,1,0,NaN,PASS

In [44]:
print("Available DQ-related variables:")

for name in sorted(globals()):
    if name.startswith("dq") and not name.startswith("__"):
        obj = globals()[name]
        print(f"{name}: {type(obj).__name__}")

print("\nCurrent persisted check results:")
display(
    con_dq.execute("""
        SELECT check_id, check_name, status, failing_rows
        FROM warehouse.dq_results
        ORDER BY check_id
    """).fetchdf()
)

Available DQ-related variables:
dq01: DataFrame
dq02: DataFrame
dq03: DataFrame
dq04: DataFrame
dq05: DataFrame
dq06: DataFrame
dq06_exception_counts: dict
dq06_review: DataFrame
dq06_total_exceptions: int
dq07: DataFrame
dq08: DataFrame
dq09: DataFrame
dq10: DataFrame
dq11: DataFrame
dq12: DataFrame
dq13: DataFrame
dq14: DataFrame
dq14_refined: DataFrame
dq14_test: DataFrame
dq_catalog: DataFrame
dq_results_to_save: DataFrame
dq_summary: DataFrame

Current persisted check results:

   check_id                          check_name   status  failing_rows
0    DQ-C01               Payroll equals ledger     FAIL             5
1    DQ-C02                     Ledger balanced     PASS             0
2    DQ-C03                 Unique payroll rows     FAIL             2
3    DQ-C04                 No orphan employees     FAIL             2
4    DQ-C05            No attendance after exit     FAIL             4
5    DQ-C06               Unpaid leave deducted     FAIL            48
6    DQ-C07                  Invoice arithmetic     FAIL             1
7    DQ-C08                  Expense arithmetic     FAIL             1
8    DQ-C09                 Task dates sensible     FAIL            20
9    DQ-C10                Leave dates sensible     FAIL             2
10   DQ-C11                  AI feeds are fresh     FAIL             5
11   DQ-C12  Dimension history does not overlap     FAIL             1
12   DQ-C13                  Pipeline freshness  BLOCKED          <NA>
13   DQ-C14                  Minimum group size     FAIL            18

In [45]:
# Confirm that the current database connections and required tables exist
required_tables = [
    "fact_payroll",
    "fact_ledger",
    "dim_employee",
    "fact_attendance_monthly",
    "fact_invoice",
    "fact_expense",
    "fact_task",
    "fact_leave",
    "fact_attrition_risk",
]

available_tables = con_dq.execute("""
    SHOW ALL TABLES
""").fetchdf()

for table in required_tables:
    found = available_tables[
        (available_tables["database"] == "pulseiq_warehouse")
        & (available_tables["schema"] == "warehouse")
        & (available_tables["name"] == table)
    ].shape[0] > 0

    print(f"{table}: {'AVAILABLE' if found else 'MISSING'}")

print("\nSource connection:")
display(
    con_dq.execute("PRAGMA database_list").fetchdf()
)

fact_payroll: AVAILABLE
fact_ledger: AVAILABLE
dim_employee: AVAILABLE
fact_attendance_monthly: AVAILABLE
fact_invoice: AVAILABLE
fact_expense: AVAILABLE
fact_task: AVAILABLE
fact_leave: AVAILABLE
fact_attrition_risk: AVAILABLE

Source connection:

,seq,name,file
0,20777,pulseiq_warehouse,C:\Users\Hp\Documents\pulseiq\05_Starter\pulseiq_warehouse.duckdb
1,22382,source_db,C:\Users\Hp\Documents\pulseiq\05_Starter\pulseiq.duckdb

In [46]:
def run_sql_check(query, connection=con_dq):
    """
    Execute a data-quality SQL query and return its failing rows.
    The query should return one row per exception.
    """
    result = connection.execute(query).fetchdf()
    return result


# Test the runner using the ledger balance check (DQ-C02)
ledger_balance_query = """
SELECT
    entry_id,
    ROUND(SUM(debit) - SUM(credit), 2) AS balance_difference
FROM warehouse.fact_ledger
GROUP BY entry_id
HAVING ABS(SUM(debit) - SUM(credit)) > 0.005
"""

dq02_rerun = run_sql_check(ledger_balance_query)

print("Check: DQ-C02 — Ledger balanced")
print("Failing entries:", len(dq02_rerun))
display(dq02_rerun.head(10))

Check: DQ-C02 — Ledger balanced
Failing entries: 0

Empty DataFrame
Columns: [entry_id, balance_difference]
Index: []

In [47]:
duplicate_payroll_query = """
SELECT
    employee_id,
    run_id,
    COUNT(*) AS row_count
FROM warehouse.fact_payroll
GROUP BY employee_id, run_id
HAVING COUNT(*) > 1
ORDER BY employee_id, run_id
"""

dq03_rerun = run_sql_check(duplicate_payroll_query)

print("Check: DQ-C03 — Unique payroll rows")
print("Duplicate employee/run groups:", len(dq03_rerun))
display(dq03_rerun)

Check: DQ-C03 — Unique payroll rows
Duplicate employee/run groups: 2

  employee_id      run_id  row_count
0    EMP-0194  PR-2026-02          2
1    EMP-0598  PR-2025-05          2

In [48]:
dq_sql_checks = {
    "DQ-C02": {
        "name": "Ledger balanced",
        "severity": "Critical",
        "query": """
            SELECT entry_id,
                   ROUND(SUM(debit) - SUM(credit), 2)
                       AS balance_difference
            FROM warehouse.fact_ledger
            GROUP BY entry_id
            HAVING ABS(SUM(debit) - SUM(credit)) > 0.005
        """
    },
    "DQ-C03": {
        "name": "Unique payroll rows",
        "severity": "Critical",
        "query": """
            SELECT employee_id, run_id, COUNT(*) AS row_count
            FROM warehouse.fact_payroll
            GROUP BY employee_id, run_id
            HAVING COUNT(*) > 1
        """
    },
    "DQ-C04": {
        "name": "No orphan employees",
        "severity": "Critical",
        "query": """
            SELECT p.payroll_item_id, p.employee_id, p.run_id
            FROM warehouse.fact_payroll p
            LEFT JOIN warehouse.dim_employee e
                ON p.employee_id = e.employee_id
            WHERE e.employee_id IS NULL
        """
    },
    "DQ-C07": {
        "name": "Invoice arithmetic",
        "severity": "Warning",
        "query": """
            SELECT invoice_id, total_amount, amount_paid, balance_due
            FROM warehouse.fact_invoice
            WHERE amount_paid > total_amount
               OR balance_due < 0
        """
    },
    "DQ-C08": {
        "name": "Expense arithmetic",
        "severity": "Warning",
        "query": """
            SELECT expense_id, amount_excl_gst, gst_amount,
                   total_amount,
                   total_amount - (amount_excl_gst + gst_amount)
                       AS difference
            FROM warehouse.fact_expense
            WHERE ABS(
                total_amount - (amount_excl_gst + gst_amount)
            ) > 0.01
        """
    },
    "DQ-C09": {
        "name": "Task dates sensible",
        "severity": "Warning",
        "query": """
            SELECT task_id, status, started_date, completed_date
            FROM warehouse.fact_task
            WHERE completed_date < started_date
               OR (
                   LOWER(TRIM(status)) = 'done'
                   AND completed_date IS NULL
               )
        """
    },
    "DQ-C10": {
        "name": "Leave dates sensible",
        "severity": "Warning",
        "query": """
            SELECT leave_request_id, start_date, end_date, status
            FROM warehouse.fact_leave
            WHERE end_date < start_date
        """
    },
    "DQ-C11": {
        "name": "AI feeds are fresh",
        "severity": "Warning",
        "query": """
            SELECT prediction_id, as_of_date
            FROM warehouse.fact_attrition_risk
            WHERE as_of_date < (
                SELECT MAX(as_of_date) - INTERVAL '7 days'
                FROM warehouse.fact_attrition_risk
            )
        """
    }
}

print("Reusable SQL checks defined:", len(dq_sql_checks))
print("Check IDs:", sorted(dq_sql_checks.keys()))

Reusable SQL checks defined: 8
Check IDs: ['DQ-C02', 'DQ-C03', 'DQ-C04', 'DQ-C07', 'DQ-C08', 'DQ-C09', 'DQ-C10', 'DQ-C11']

In [49]:
# Execute each reusable SQL definition against current warehouse data
dq_rerun_results = {}
dq_rerun_summary = []

for check_id, check in dq_sql_checks.items():
    try:
        exceptions = run_sql_check(check["query"])
        dq_rerun_results[check_id] = exceptions

        dq_rerun_summary.append({
            "check_id": check_id,
            "check_name": check["name"],
            "severity": check["severity"],
            "status": "PASS" if exceptions.empty else "FAIL",
            "failing_rows": len(exceptions),
            "execution_error": None
        })

    except Exception as exc:
        dq_rerun_summary.append({
            "check_id": check_id,
            "check_name": check["name"],
            "severity": check["severity"],
            "status": "ERROR",
            "failing_rows": None,
            "execution_error": str(exc)
        })

dq_rerun_summary_df = pd.DataFrame(dq_rerun_summary)

display(
    dq_rerun_summary_df.sort_values("check_id").reset_index(drop=True)
)

,check_id,check_name,severity,status,failing_rows,execution_error
0,DQ-C02,Ledger balanced,Critical,PASS,0,None
1,DQ-C03,Unique payroll rows,Critical,FAIL,2,None
2,DQ-C04,No orphan employees,Critical,FAIL,2,None
3,DQ-C07,Invoice arithmetic,Warning,FAIL,1,None
4,DQ-C08,Expense arithmetic,Warning,FAIL,1,None
5,DQ-C09,Task dates sensible,Warning,FAIL,20,None
6,DQ-C10,Leave dates sensible,Warning,FAIL,2,None
7,DQ-C11,AI feeds are fresh,Warning,FAIL,5,None

In [50]:
dq_sql_checks.update({
    "DQ-C05": {
        "name": "No attendance after exit",
        "severity": "Warning",
        "query": """
            SELECT
                a.attendance_fact_id,
                a.employee_id,
                a.period_end_date,
                e.exit_date
            FROM warehouse.fact_attendance_monthly a
            JOIN warehouse.dim_employee e
                ON a.employee_key = e.employee_key
            WHERE e.exit_date IS NOT NULL
              AND a.period_end_date > e.exit_date
        """
    },
    "DQ-C01": {
        "name": "Payroll equals ledger",
        "severity": "Critical",
        "query": """
            WITH payroll_monthly AS (
                SELECT
                    DATE_TRUNC('month', period_end_date)::DATE AS month,
                    SUM(employer_cost) AS payroll_cost
                FROM warehouse.fact_payroll
                GROUP BY 1
            ),
            ledger_monthly AS (
                SELECT
                    DATE_TRUNC('month', entry_date)::DATE AS month,
                    SUM(signed_amount_debit_positive) AS ledger_cost
                FROM warehouse.fact_ledger
                WHERE account_code IN (5001, 5002, 5003, 5004, 5005)
                GROUP BY 1
            )
            SELECT
                COALESCE(p.month, l.month) AS month,
                p.payroll_cost,
                l.ledger_cost,
                COALESCE(p.payroll_cost, 0)
                    - COALESCE(l.ledger_cost, 0) AS difference
            FROM payroll_monthly p
            FULL OUTER JOIN ledger_monthly l USING (month)
            WHERE ABS(
                COALESCE(p.payroll_cost, 0)
                - COALESCE(l.ledger_cost, 0)
            ) > 0.01
        """
    }
})

print("Reusable SQL checks defined:", len(dq_sql_checks))
print("Check IDs:", sorted(dq_sql_checks.keys()))

Reusable SQL checks defined: 10
Check IDs: ['DQ-C01', 'DQ-C02', 'DQ-C03', 'DQ-C04', 'DQ-C05', 'DQ-C07', 'DQ-C08', 'DQ-C09', 'DQ-C10', 'DQ-C11']

In [51]:
dq_sql_checks["DQ-C12"] = {
    "name": "Dimension history does not overlap",
    "severity": "Critical",
    "query": """
        SELECT
            earlier.employee_id,
            earlier.employee_key AS earlier_key,
            earlier.valid_from AS earlier_valid_from,
            earlier.valid_to AS earlier_valid_to,
            later.employee_key AS later_key,
            later.valid_from AS later_valid_from,
            later.valid_to AS later_valid_to
        FROM warehouse.dim_employee earlier
        JOIN warehouse.dim_employee later
          ON earlier.employee_id = later.employee_id
         AND earlier.employee_key < later.employee_key
         AND earlier.valid_from < COALESCE(
                later.valid_to, DATE '9999-12-31'
             )
         AND later.valid_from < COALESCE(
                earlier.valid_to, DATE '9999-12-31'
             )
    """
}

print("Reusable SQL checks defined:", len(dq_sql_checks))
print("DQ-C12 definition added:", "DQ-C12" in dq_sql_checks)

Reusable SQL checks defined: 11
DQ-C12 definition added: True

In [52]:
dq_sql_checks["DQ-C06"] = {
    "name": "Unpaid leave deducted",
    "severity": "Warning",
    "query": """
        WITH attendance AS (
            SELECT
                employee_id,
                period_end_date,
                SUM(unpaid_absence_days) AS unpaid_days
            FROM warehouse.fact_attendance_monthly
            GROUP BY employee_id, period_end_date
        ),
        payroll AS (
            SELECT
                employee_id,
                period_end_date,
                SUM(lop_days) AS lop_days
            FROM warehouse.fact_payroll
            GROUP BY employee_id, period_end_date
        )
        SELECT
            COALESCE(a.employee_id, p.employee_id) AS employee_id,
            COALESCE(a.period_end_date, p.period_end_date)
                AS period_end_date,
            a.unpaid_days,
            p.lop_days,
            CASE
                WHEN a.employee_id IS NULL THEN 'MISSING_ATTENDANCE'
                WHEN p.employee_id IS NULL THEN 'MISSING_PAYROLL'
                WHEN ABS(a.unpaid_days - p.lop_days) > 0.5
                    THEN 'DAY_MISMATCH'
            END AS issue_type
        FROM attendance a
        FULL OUTER JOIN payroll p
          ON a.employee_id = p.employee_id
         AND a.period_end_date = p.period_end_date
        WHERE a.employee_id IS NULL
           OR p.employee_id IS NULL
           OR ABS(a.unpaid_days - p.lop_days) > 0.5
    """
}

print("Reusable SQL checks defined:", len(dq_sql_checks))
print("Check IDs:", sorted(dq_sql_checks.keys()))

Reusable SQL checks defined: 12
Check IDs: ['DQ-C01', 'DQ-C02', 'DQ-C03', 'DQ-C04', 'DQ-C05', 'DQ-C06', 'DQ-C07', 'DQ-C08', 'DQ-C09', 'DQ-C10', 'DQ-C11', 'DQ-C12']

In [ ]:
dq_rerun_results = {}
dq_rerun_summary = []

for check_id, check in sorted(dq_sql_checks.items()):
    try:
        exceptions = run_sql_check(check["query"])
        dq_rerun_results[check_id] = exceptions

        dq_rerun_summary.append({
            "check_id": check_id,
            "check_name": check["name"],
            "severity": check["severity"],
            "status": "PASS" if exceptions.empty else "FAIL",
            "failing_rows": len(exceptions),
            "execution_error": None
        })

    except Exception as exc:
        dq_rerun_summary.append({
            "check_id": check_id,
            "check_name": check["name"],
            "severity": check["severity"],
            "status": "ERROR",
            "failing_rows": None,
            "execution_error": str(exc)
        })

dq_rerun_summary_df = pd.DataFrame(dq_rerun_summary)

display(
    dq_rerun_summary_df.sort_values("check_id").reset_index(drop=True)
)

In [ ]:
dq05_rerun = dq_rerun_results["DQ-C05"]

print("Total attendance-after-exit rows:", len(dq05_rerun))

planted_attendance_ids = {
    "FA-X0001",
    "FA-X0002",
    "FA-X0003",
    "FA-X0004"
}

detected_attendance_ids = set(
    dq05_rerun["attendance_fact_id"].astype(str)
)

print(
    "Planted records detected:",
    len(planted_attendance_ids & detected_attendance_ids)
)
print(
    "Planted records missing:",
    sorted(planted_attendance_ids - detected_attendance_ids)
)

print("\nSample exceptions:")
display(dq05_rerun.head(15))

In [ ]:
dq05_review = dq_rerun_results["DQ-C05"].copy()

dq05_review["days_after_exit"] = (
    pd.to_datetime(dq05_review["period_end_date"])
    - pd.to_datetime(dq05_review["exit_date"])
).dt.days

dq05_review["planted_issue"] = dq05_review[
    "attendance_fact_id"
].isin(planted_attendance_ids)

print("Total flagged:", len(dq05_review))
print("Planted exceptions:", int(dq05_review["planted_issue"].sum()))
print("Other flagged records:", int((~dq05_review["planted_issue"]).sum()))

display(
    dq05_review[
        [
            "attendance_fact_id",
            "employee_id",
            "period_end_date",
            "exit_date",
            "days_after_exit",
            "planted_issue"
        ]
    ].sort_values(
        ["planted_issue", "days_after_exit"],
        ascending=[False, True]
    ).head(20)
)

In [ ]:
print("Attendance table columns:")
display(
    con_dq.execute("""
        DESCRIBE warehouse.fact_attendance_monthly
    """).fetchdf()
)

print("\nDQ-C05 catalog definition:")
display(
    dq_catalog[
        dq_catalog.astype(str)
        .apply(
            lambda col: col.str.contains("DQ-C05", regex=False).any()
        )
        .any(axis=1)
    ]
)

In [ ]:
print("dq_catalog type:", type(dq_catalog))
print("\nCatalog preview:")
display(dq_catalog.head(5))

print("\nSearch catalog for DQ-C05:")
print(
    dq_catalog[
        dq_catalog.astype(str).str.contains(
            "DQ-C05", case=False, regex=False, na=False
        )
    ]
)

In [ ]:
dq_sql_checks["DQ-C05"] = """
SELECT
    a.attendance_fact_id,
    a.employee_id,
    a.period_end_date,
    d.exit_date
FROM warehouse.fact_attendance_monthly a
JOIN warehouse.dim_employee d
    ON a.employee_id = d.employee_id
   AND d.is_current = 'Y'
WHERE d.exit_date IS NOT NULL
  AND DATE_TRUNC('month', a.period_end_date)
      > DATE_TRUNC('month', d.exit_date)
"""

dq05_corrected = run_sql_check(dq_sql_checks["DQ-C05"])

planted_attendance_ids = {
    "FA-X0001", "FA-X0002", "FA-X0003", "FA-X0004"
}

detected_ids = set(dq05_corrected["attendance_fact_id"])
planted_detected = detected_ids.intersection(planted_attendance_ids)

print("Corrected DQ-C05 exceptions:", len(dq05_corrected))
print("Planted exceptions detected:", len(planted_detected))
print("Planted exceptions missed:", planted_attendance_ids - detected_ids)

display(dq05_corrected.head(10))

In [ ]:
dq_rerun_results = {}
dq_rerun_summary = []

for check_id, query in dq_sql_checks.items():
    try:
        result = run_sql_check(query)
        dq_rerun_results[check_id] = result

        dq_rerun_summary.append({
            "check_id": check_id,
            "status": "PASS" if result.empty else "FAIL",
            "failing_rows": len(result),
            "error": None
        })

    except Exception as e:
        dq_rerun_summary.append({
            "check_id": check_id,
            "status": "ERROR",
            "failing_rows": None,
            "error": str(e)
        })

dq_rerun_summary_df = pd.DataFrame(dq_rerun_summary)

display(
    dq_rerun_summary_df.sort_values("check_id").reset_index(drop=True)
)

print("\nTotal SQL checks executed:", len(dq_sql_checks))
print("Checks passed:", (dq_rerun_summary_df["status"] == "PASS").sum())
print("Checks failed:", (dq_rerun_summary_df["status"] == "FAIL").sum())
print("Checks with errors:", (dq_rerun_summary_df["status"] == "ERROR").sum())

In [ ]:
import inspect

print("run_sql_check definition:")
print(inspect.getsource(run_sql_check))

print("\nType of connection:", type(con_dq))
print("Number of registered checks:", len(dq_sql_checks))

print("\nDQ-C01 query type:", type(dq_sql_checks["DQ-C01"]))
print("DQ-C01 query preview:")
print(repr(dq_sql_checks["DQ-C01"])[:500])

In [ ]:
def run_sql_check(check, connection=con_dq):
    """
    Execute a data-quality SQL check.
    Accepts either a SQL string or a dictionary containing 'query'.
    Returns one row per exception.
    """
    if isinstance(check, dict):
        query = check["query"]
    else:
        query = check

    if not isinstance(query, str):
        raise TypeError(
            f"Expected SQL string, received {type(query).__name__}"
        )

    return connection.execute(query).fetchdf()


print("SQL runner updated successfully.")

# Test one metadata-based check
test_result = run_sql_check(dq_sql_checks["DQ-C01"])
print("DQ-C01 execution successful.")
print("Exception rows:", len(test_result))
display(test_result.head())

In [ ]:
dq_rerun_results = {}
dq_rerun_summary = []

for check_id, check in dq_sql_checks.items():
    try:
        result = run_sql_check(check)
        dq_rerun_results[check_id] = result

        dq_rerun_summary.append({
            "check_id": check_id,
            "status": "PASS" if result.empty else "FAIL",
            "failing_rows": len(result),
            "error": None
        })

    except Exception as e:
        dq_rerun_summary.append({
            "check_id": check_id,
            "status": "ERROR",
            "failing_rows": None,
            "error": str(e)
        })

dq_rerun_summary_df = pd.DataFrame(dq_rerun_summary)

display(
    dq_rerun_summary_df.sort_values("check_id").reset_index(drop=True)
)

print("\nTotal checks:", len(dq_sql_checks))
print("PASS:", (dq_rerun_summary_df["status"] == "PASS").sum())
print("FAIL:", (dq_rerun_summary_df["status"] == "FAIL").sum())
print("ERROR:", (dq_rerun_summary_df["status"] == "ERROR").sum())

In [ ]:
# Verify key planted issues against the latest automated results

planted_checks = {
    "DQ-C02": "Ledger balanced",
    "DQ-C03": "Duplicate payroll rows",
    "DQ-C04": "Orphan employees",
    "DQ-C05": "Attendance after exit",
    "DQ-C07": "Invoice arithmetic",
    "DQ-C08": "Expense arithmetic",
    "DQ-C09": "Task date errors",
    "DQ-C10": "Leave date errors",
    "DQ-C11": "Stale predictions",
    "DQ-C12": "Dimension history overlap",
}

for check_id, description in planted_checks.items():
    result = dq_rerun_results[check_id]
    print(f"{check_id} | {description} | Exceptions: {len(result)}")

# Confirm the four attendance planted IDs are all detected
planted_attendance_ids = {
    "FA-X0001", "FA-X0002", "FA-X0003", "FA-X0004"
}

detected_attendance_ids = set(
    dq_rerun_results["DQ-C05"]["attendance_fact_id"]
)

print("\nDQ-C05 planted detection:")
print("Detected:", len(planted_attendance_ids & detected_attendance_ids), "/ 4")
print("Missed:", planted_attendance_ids - detected_attendance_ids)

In [ ]:
display(
    dq_summary[
        dq_summary["check_id"].isin(["DQ-C13", "DQ-C14"])
    ].to_string(index=False)
)

print("\nExisting summary columns:")
print(dq_summary.columns.tolist())

print("\nAvailable warehouse tables matching ETL/run/log:")
display(
    con_dq.execute("""
        SELECT database_name, schema_name, table_name
        FROM duckdb_tables()
        WHERE lower(table_name) LIKE '%etl%'
           OR lower(table_name) LIKE '%run%log%'
        ORDER BY database_name, schema_name, table_name
    """).fetchdf()
)

In [ ]:
# Start with the latest automated SQL results
final_dq_summary = dq_rerun_summary_df.copy()

# Standardize column names and attach catalog metadata
final_dq_summary = final_dq_summary.rename(
    columns={
        "status": "status",
        "failing_rows": "failing_rows"
    }
)

final_dq_summary["check_name"] = final_dq_summary["check_id"].map(
    dq_catalog.set_index("check_id")["check_name"]
)
final_dq_summary["severity"] = final_dq_summary["check_id"].map(
    dq_catalog.set_index("check_id")["severity"]
)
final_dq_summary["reason"] = final_dq_summary["error"]

# Remove the execution-error column after preserving its contents
final_dq_summary = final_dq_summary[
    ["check_id", "check_name", "severity", "status", "failing_rows", "reason"]
]

# Add DQ-C13: no load-log table means freshness cannot be verified
final_dq_summary.loc[len(final_dq_summary)] = {
    "check_id": "DQ-C13",
    "check_name": "Pipeline freshness",
    "severity": "Critical",
    "status": "BLOCKED",
    "failing_rows": None,
    "reason": "etl_run_log table is unavailable; freshness cannot be verified."
}

# Add DQ-C14: partial implementation only
final_dq_summary.loc[len(final_dq_summary)] = {
    "check_id": "DQ-C14",
    "check_name": "Minimum group size",
    "severity": "Critical",
    "status": "PARTIAL",
    "failing_rows": 18,
    "reason": (
        "Department-month headcount suppression tested: "
        "180 RELEASE, 18 SUPPRESS using threshold 5. "
        "Metric-specific thresholds and aggregation grains remain incomplete."
    )
}

final_dq_summary = (
    final_dq_summary
    .sort_values("check_id")
    .reset_index(drop=True)
)

display(final_dq_summary)

print("\nTotal catalog checks:", len(final_dq_summary))
print("\nStatus counts:")
display(final_dq_summary["status"].value_counts().rename_axis("status").to_frame("count"))

In [ ]:
# Distinguish successful execution from data-quality findings
final_dq_summary["execution_status"] = "EXECUTED"

final_dq_summary.loc[
    final_dq_summary["check_id"] == "DQ-C13",
    "execution_status"
] = "BLOCKED"

final_dq_summary.loc[
    final_dq_summary["check_id"] == "DQ-C14",
    "execution_status"
] = "PARTIAL"

# Add clear interpretation for the report
final_dq_summary["interpretation"] = final_dq_summary["status"].map({
    "PASS": "Executed; no exceptions found",
    "FAIL": "Executed; data-quality exceptions found",
    "BLOCKED": "Could not evaluate with available data",
    "PARTIAL": "Partially implemented; further validation required",
    "ERROR": "SQL execution error"
})

display(
    final_dq_summary[
        [
            "check_id",
            "check_name",
            "severity",
            "status",
            "execution_status",
            "failing_rows",
            "interpretation"
        ]
    ]
)

print("\nSummary:")
print("Total checks:", len(final_dq_summary))
print("SQL checks executed:", (final_dq_summary["execution_status"] == "EXECUTED").sum())
print("Blocked checks:", (final_dq_summary["execution_status"] == "BLOCKED").sum())
print("Partial checks:", (final_dq_summary["execution_status"] == "PARTIAL").sum())

In [ ]:
# Save the consolidated 14-check summary to DuckDB
con_dq.register("final_dq_summary_temp", final_dq_summary)

con_dq.execute("""
    CREATE OR REPLACE TABLE warehouse.dq_results AS
    SELECT *
    FROM final_dq_summary_temp
""")

con_dq.unregister("final_dq_summary_temp")

print("Saved table: warehouse.dq_results")

# Verify saved record count and statuses
print("\nSaved record count:")
print(
    con_dq.execute("""
        SELECT COUNT(*) AS total_checks
        FROM warehouse.dq_results
    """).fetchdf()
)

print("\nSaved status summary:")
display(
    con_dq.execute("""
        SELECT status, COUNT(*) AS check_count
        FROM warehouse.dq_results
        GROUP BY status
        ORDER BY status
    """).fetchdf()
)

print("\nSaved report preview:")
display(
    con_dq.execute("""
        SELECT check_id, check_name, severity, status,
               execution_status, failing_rows
        FROM warehouse.dq_results
        ORDER BY check_id
    """).fetchdf()
)

In [ ]:
print("Planted-issue coverage report exists:")
print(
    r"C:\Users\Hp\Documents\pulseiq\04_Validation_Vault"
    r"\PQ-03_planted_issue_coverage.csv"
)

coverage_check = pd.read_csv(
    r"C:\Users\Hp\Documents\pulseiq\04_Validation_Vault"
    r"\PQ-03_planted_issue_coverage.csv"
)

print("\nCoverage report shape:", coverage_check.shape)
print("\nCoverage report columns:")
print(coverage_check.columns.tolist())

display(coverage_check)

In [ ]:
from pathlib import Path
import json

notebook_path = Path(
    r"C:\Users\Hp\Documents\pulseiq"
    r"\PQ-03_Data_Quality_Gatekeeper.ipynb"
)

coverage_path = Path(
    r"C:\Users\Hp\Documents\pulseiq\04_Validation_Vault"
    r"\PQ-03_planted_issue_coverage.csv"
)

print("Notebook exists:", notebook_path.exists())
print("Coverage report exists:", coverage_path.exists())

coverage_check = pd.read_csv(coverage_path)

print("Planted issue categories:", len(coverage_check))
print("Categories passing:", (coverage_check["status"] == "PASS").sum())
print("Total missed records:", coverage_check["missed_count"].sum())

saved_checks = con_dq.execute("""
    SELECT COUNT(*) AS total_checks
    FROM warehouse.dq_results
""").fetchone()[0]

print("Saved DQ checks:", saved_checks)

if notebook_path.exists():
    with notebook_path.open("r", encoding="utf-8") as f:
        notebook_json = json.load(f)

    print("Notebook cells:", len(notebook_json["cells"]))
    print("Notebook JSON valid: True")